# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Cadastros_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cadastros_menu(object):
    def setupUi(self, cadastros_menu):
        cadastros_menu.setObjectName("cadastros_menu")
        cadastros_menu.resize(1290, 841)
        cadastros_menu.setMinimumSize(QtCore.QSize(1290, 841))
        cadastros_menu.setMaximumSize(QtCore.QSize(1290, 841))
        cadastros_menu.setStyleSheet("background-color: rgb(255, 255, 255);")
        cadastros_menu.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(cadastros_menu)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_Borda = QtWidgets.QLabel(self.centralwidget)
        self.Label_Borda.setGeometry(QtCore.QRect(0, 783, 1290, 18))
        self.Label_Borda.setText("")
        self.Label_Borda.setPixmap(QtGui.QPixmap("Imagens/Borda.png"))
        self.Label_Borda.setScaledContents(True)
        self.Label_Borda.setObjectName("Label_Borda")
        self.label_fundo = QtWidgets.QLabel(self.centralwidget)
        self.label_fundo.setGeometry(QtCore.QRect(20, 0, 1251, 761))
        font = QtGui.QFont()
        font.setFamily("Bosch Sans Bold")
        font.setPointSize(65)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_fundo.setFont(font)
        self.label_fundo.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:7px;\n"
"border-radius: 0px;\n"
"background-color: rgb(255, 255, 255);")
        self.label_fundo.setText("")
        self.label_fundo.setObjectName("label_fundo")
        self.label_preto = QtWidgets.QLabel(self.centralwidget)
        self.label_preto.setGeometry(QtCore.QRect(350, 0, 921, 101))
        self.label_preto.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:6px;\n"
"\n"
"\n"
"font: 75 35pt \"Bosch Sans Bold\";\n"
"background-color: rgb(0,0,0);")
        self.label_preto.setObjectName("label_preto")
        self.label_fundo_cinza = QtWidgets.QLabel(self.centralwidget)
        self.label_fundo_cinza.setGeometry(QtCore.QRect(20, -1, 331, 761))
        self.label_fundo_cinza.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:6px;\n"
"background-color: rgb(101, 106, 111);\n"
"\n"
"font: 75 80pt \"Bosch Sans Bold\";\n"
"")
        self.label_fundo_cinza.setText("")
        self.label_fundo_cinza.setScaledContents(True)
        self.label_fundo_cinza.setObjectName("label_fundo_cinza")
        self.botao_adicionar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_adicionar.setGeometry(QtCore.QRect(70, 60, 230, 225))
        self.botao_adicionar.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;\n"
"font: 75 65pt \"Bosch Sans Bold\";\n"
"border-radius: 0px;\n"
"background-color: rgb(255, 255, 255);")
        self.botao_adicionar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imagens/Adicionar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_adicionar.setIcon(icon)
        self.botao_adicionar.setIconSize(QtCore.QSize(220, 217))
        self.botao_adicionar.setObjectName("botao_adicionar")
        self.botao_editar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_editar.setGeometry(QtCore.QRect(70, 340, 230, 225))
        self.botao_editar.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;\n"
"font: 75 65pt \"Bosch Sans Bold\";\n"
"border-radius: 0px;\n"
"background-color: rgb(255, 255, 255);")
        self.botao_editar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("imagens/Editar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_editar.setIcon(icon1)
        self.botao_editar.setIconSize(QtCore.QSize(220, 217))
        self.botao_editar.setShortcut("")
        self.botao_editar.setObjectName("botao_editar")
        self.label_edv = QtWidgets.QLabel(self.centralwidget)
        self.label_edv.setGeometry(QtCore.QRect(360, 10, 231, 71))
        self.label_edv.setStyleSheet("border-style: inside;\n"
"border-color: rgb(255, 255, 255);\n"
"border-width:6px;\n"
"\n"
"\n"
"font: 75 35pt \"Bosch Sans Bold\";\n"
"background-color: rgb(0,0,0);")
        self.label_edv.setObjectName("label_edv")
        self.label_usuario = QtWidgets.QLabel(self.centralwidget)
        self.label_usuario.setGeometry(QtCore.QRect(660, 10, 261, 71))
        self.label_usuario.setStyleSheet("border-style: inside;\n"
"border-color: rgb(255, 255, 255);\n"
"border-width:6px;\n"
"\n"
"\n"
"font: 75 35pt \"Bosch Sans Bold\";\n"
"background-color: rgb(0,0,0);")
        self.label_usuario.setObjectName("label_usuario")
        self.label_classe = QtWidgets.QLabel(self.centralwidget)
        self.label_classe.setGeometry(QtCore.QRect(1020, 10, 231, 71))
        self.label_classe.setStyleSheet("border-style: inside;\n"
"border-color: rgb(255, 255, 255);\n"
"border-width:6px;\n"
"\n"
"\n"
"font: 75 35pt \"Bosch Sans Bold\";\n"
"background-color: rgb(0,0,0);")
        self.label_classe.setObjectName("label_classe")
        self.botao_voltar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_voltar.setGeometry(QtCore.QRect(60, 650, 251, 71))
        self.botao_voltar.setStyleSheet("border-style: outset;\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border-width:6px;\n"
"\n"
"\n"
"font: 75 35pt \"Bosch Sans Bold\";\n"
"background-color: rgb(0,0,0);")
        self.botao_voltar.setObjectName("botao_voltar")
        self.tabela = QtWidgets.QTableWidget(self.centralwidget)
        self.tabela.setGeometry(QtCore.QRect(360, 110, 891, 631))
        self.tabela.setStyleSheet("font: 75 20pt \"Bosch Sans Bold\";")
        self.tabela.setObjectName("tabela")
        self.tabela.setColumnCount(2)
        self.tabela.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabela.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela.setHorizontalHeaderItem(1, item)
        cadastros_menu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(cadastros_menu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1290, 21))
        self.menubar.setObjectName("menubar")
        cadastros_menu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(cadastros_menu)
        self.statusbar.setObjectName("statusbar")
        cadastros_menu.setStatusBar(self.statusbar)

        self.retranslateUi(cadastros_menu)
        QtCore.QMetaObject.connectSlotsByName(cadastros_menu)

    def retranslateUi(self, cadastros_menu):
        _translate = QtCore.QCoreApplication.translate
        cadastros_menu.setWindowTitle(_translate("cadastros_menu", "MainWindow"))
        self.label_preto.setText(_translate("cadastros_menu", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_edv.setText(_translate("cadastros_menu", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">EDV</span></p></body></html>"))
        self.label_usuario.setText(_translate("cadastros_menu", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">USUÁRIO</span></p></body></html>"))
        self.label_classe.setText(_translate("cadastros_menu", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">CLASSE</span></p></body></html>"))
        self.botao_voltar.setWhatsThis(_translate("cadastros_menu", "<html><head/><body><p><span style=\" color:#ffffff;\">OI</span></p></body></html>"))
        self.botao_voltar.setText(_translate("cadastros_menu", "VOLTAR"))
        item = self.tabela.horizontalHeaderItem(0)
        item.setText(_translate("cadastros_menu", "Nome"))
        item = self.tabela.horizontalHeaderItem(1)
        item.setText(_translate("cadastros_menu", "EDV"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    cadastros_menu = QtWidgets.QMainWindow()
    ui = Ui_cadastros_menu()
    ui.setupUi(cadastros_menu)
    cadastros_menu.show()
    sys.exit(app.exec_())
