# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Cadastros_adicionar_ficha01.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cadastros_adicionar_ficha01(object):
    def setupUi(self, cadastros_adicionar_ficha01):
        cadastros_adicionar_ficha01.setObjectName("cadastros_adicionar_ficha01")
        cadastros_adicionar_ficha01.resize(1290, 841)
        cadastros_adicionar_ficha01.setMinimumSize(QtCore.QSize(1290, 841))
        cadastros_adicionar_ficha01.setMaximumSize(QtCore.QSize(1290, 841))
        cadastros_adicionar_ficha01.setStyleSheet("background-color: rgb(255, 255, 255);")
        cadastros_adicionar_ficha01.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(cadastros_adicionar_ficha01)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_Borda = QtWidgets.QLabel(self.centralwidget)
        self.Label_Borda.setGeometry(QtCore.QRect(0, 783, 1290, 18))
        self.Label_Borda.setText("")
        self.Label_Borda.setPixmap(QtGui.QPixmap("Imagens/Borda.png"))
        self.Label_Borda.setScaledContents(True)
        self.Label_Borda.setObjectName("Label_Borda")
        self.label_fundo = QtWidgets.QLabel(self.centralwidget)
        self.label_fundo.setGeometry(QtCore.QRect(20, 10, 1251, 761))
        font = QtGui.QFont()
        font.setFamily("Bosch Sans Bold")
        font.setPointSize(65)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_fundo.setFont(font)
        self.label_fundo.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:7px;\n"
"border-radius: 0px;\n"
"background-color: rgb(224, 227, 229);")
        self.label_fundo.setText("")
        self.label_fundo.setObjectName("label_fundo")
        self.label_imagem_classe = QtWidgets.QLabel(self.centralwidget)
        self.label_imagem_classe.setGeometry(QtCore.QRect(740, 10, 531, 761))
        self.label_imagem_classe.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:6px;\n"
"\n"
"\n"
"")
        self.label_imagem_classe.setText("")
        self.label_imagem_classe.setPixmap(QtGui.QPixmap("imagens/Responsavel_02.png"))
        self.label_imagem_classe.setScaledContents(True)
        self.label_imagem_classe.setObjectName("label_imagem_classe")
        self.botao_avancar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_avancar.setGeometry(QtCore.QRect(50, 600, 281, 151))
        self.botao_avancar.setStyleSheet("border-style: outset;\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:6px;\n"
"border-radius: 30px;\n"
"\n"
"font: 75 35pt \"Bosch Sans Bold\";\n"
"background-color: rgb(0,136,74);")
        self.botao_avancar.setObjectName("botao_avancar")
        self.lineEdit_nome = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nome.setGeometry(QtCore.QRect(70, 60, 631, 131))
        self.lineEdit_nome.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:6px;\n"
"background-color: rgb(193, 194, 204);\n"
"\n"
"font: 75 35pt \"Bosch Sans Bold\";\n"
"")
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.lineEdit_data_nascimento = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_data_nascimento.setGeometry(QtCore.QRect(70, 230, 631, 131))
        self.lineEdit_data_nascimento.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:6px;\n"
"background-color: rgb(193, 194, 204);\n"
"\n"
"font: 75 35pt \"Bosch Sans Bold\";\n"
"")
        self.lineEdit_data_nascimento.setObjectName("lineEdit_data_nascimento")
        self.botao_cancelar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_cancelar.setGeometry(QtCore.QRect(410, 600, 291, 141))
        self.botao_cancelar.setStyleSheet("border-style: outset;\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:6px;\n"
"border-radius: 30px;\n"
"\n"
"font: 75 34pt \"Bosch Sans Bold\";\n"
"background-color: rgb(255,207,0);")
        self.botao_cancelar.setObjectName("botao_cancelar")
        self.lineEdit_edv = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_edv.setGeometry(QtCore.QRect(70, 400, 631, 131))
        self.lineEdit_edv.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:6px;\n"
"background-color: rgb(193, 194, 204);\n"
"\n"
"font: 75 35pt \"Bosch Sans Bold\";\n"
"")
        self.lineEdit_edv.setObjectName("lineEdit_edv")
        cadastros_adicionar_ficha01.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(cadastros_adicionar_ficha01)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1290, 21))
        self.menubar.setObjectName("menubar")
        cadastros_adicionar_ficha01.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(cadastros_adicionar_ficha01)
        self.statusbar.setObjectName("statusbar")
        cadastros_adicionar_ficha01.setStatusBar(self.statusbar)

        self.retranslateUi(cadastros_adicionar_ficha01)
        QtCore.QMetaObject.connectSlotsByName(cadastros_adicionar_ficha01)

    def retranslateUi(self, cadastros_adicionar_ficha01):
        _translate = QtCore.QCoreApplication.translate
        cadastros_adicionar_ficha01.setWindowTitle(_translate("cadastros_adicionar_ficha01", "Cadastro_Classe"))
        self.botao_avancar.setWhatsThis(_translate("cadastros_adicionar_ficha01", "<html><head/><body><p><span style=\" color:#ffffff;\">OI</span></p></body></html>"))
        self.botao_avancar.setText(_translate("cadastros_adicionar_ficha01", "AVANÇAR"))
        self.lineEdit_nome.setText(_translate("cadastros_adicionar_ficha01", "     NOME COMPLETO"))
        self.lineEdit_data_nascimento.setText(_translate("cadastros_adicionar_ficha01", "  DATA DE NASCIMENTO"))
        self.botao_cancelar.setWhatsThis(_translate("cadastros_adicionar_ficha01", "<html><head/><body><p><span style=\" color:#ffffff;\">OI</span></p></body></html>"))
        self.botao_cancelar.setText(_translate("cadastros_adicionar_ficha01", "CANCELAR"))
        self.lineEdit_edv.setText(_translate("cadastros_adicionar_ficha01", "                  EDV"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    cadastros_adicionar_ficha01 = QtWidgets.QMainWindow()
    ui = Ui_cadastros_adicionar_ficha01()
    ui.setupUi(cadastros_adicionar_ficha01)
    cadastros_adicionar_ficha01.show()
    sys.exit(app.exec_())
