# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Cadastros_menu_adicionar.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cadastros_classes(object):
    def setupUi(self, cadastros_classes):
        cadastros_classes.setObjectName("cadastros_classes")
        cadastros_classes.resize(1290, 841)
        cadastros_classes.setMinimumSize(QtCore.QSize(1290, 841))
        cadastros_classes.setMaximumSize(QtCore.QSize(1290, 841))
        cadastros_classes.setStyleSheet("background-color: rgb(255, 255, 255);")
        cadastros_classes.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(cadastros_classes)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_Borda = QtWidgets.QLabel(self.centralwidget)
        self.Label_Borda.setGeometry(QtCore.QRect(0, 783, 1290, 18))
        self.Label_Borda.setText("")
        self.Label_Borda.setPixmap(QtGui.QPixmap("Imagens/Borda.png"))
        self.Label_Borda.setScaledContents(True)
        self.Label_Borda.setObjectName("Label_Borda")
        self.label_fundo = QtWidgets.QLabel(self.centralwidget)
        self.label_fundo.setGeometry(QtCore.QRect(20, 10, 1251, 761))
        font = QtGui.QFont()
        font.setFamily("Bosch Sans Bold")
        font.setPointSize(65)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_fundo.setFont(font)
        self.label_fundo.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:7px;\n"
"border-radius: 0px;\n"
"background-color: rgb(224, 227, 229);")
        self.label_fundo.setText("")
        self.label_fundo.setObjectName("label_fundo")
        self.label_fundo_cinza = QtWidgets.QLabel(self.centralwidget)
        self.label_fundo_cinza.setGeometry(QtCore.QRect(20, 9, 1251, 171))
        self.label_fundo_cinza.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:6px;\n"
"background-color: rgb(193, 194, 204);\n"
"\n"
"font: 75 80pt \"Bosch Sans Bold\";\n"
"")
        self.label_fundo_cinza.setText("")
        self.label_fundo_cinza.setScaledContents(True)
        self.label_fundo_cinza.setObjectName("label_fundo_cinza")
        self.botao_aprendiz = QtWidgets.QPushButton(self.centralwidget)
        self.botao_aprendiz.setGeometry(QtCore.QRect(60, 300, 249, 250))
        self.botao_aprendiz.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;\n"
"font: 75 65pt \"Bosch Sans Bold\";\n"
"border-radius: 0px;\n"
"background-color: rgb(255, 255, 255);")
        self.botao_aprendiz.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imagens/Aprendiz.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_aprendiz.setIcon(icon)
        self.botao_aprendiz.setIconSize(QtCore.QSize(240, 240))
        self.botao_aprendiz.setShortcut("")
        self.botao_aprendiz.setObjectName("botao_aprendiz")
        self.label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo.setGeometry(QtCore.QRect(180, 20, 931, 141))
        self.label_titulo.setStyleSheet("border-style: inside;\n"
"border-color: rgb(255, 255, 255);\n"
"border-width:6px;\n"
"background-color: rgb(193, 194, 204);\n"
"\n"
"font: 75 pt \"Bosch Sans Bold\";\n"
"")
        self.label_titulo.setObjectName("label_titulo")
        self.botao_voltar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_voltar.setGeometry(QtCore.QRect(50, 650, 261, 101))
        self.botao_voltar.setStyleSheet("border-style: outset;\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border-width:6px;\n"
"\n"
"\n"
"font: 75 35pt \"Bosch Sans Bold\";\n"
"background-color: rgb(0,0,0);")
        self.botao_voltar.setObjectName("botao_voltar")
        self.botao_meio_oficial = QtWidgets.QPushButton(self.centralwidget)
        self.botao_meio_oficial.setGeometry(QtCore.QRect(368, 300, 249, 250))
        self.botao_meio_oficial.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;\n"
"font: 75 65pt \"Bosch Sans Bold\";\n"
"border-radius: 0px;\n"
"background-color: rgb(255, 255, 255);")
        self.botao_meio_oficial.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("imagens/Meio_oficial.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_meio_oficial.setIcon(icon1)
        self.botao_meio_oficial.setIconSize(QtCore.QSize(240, 240))
        self.botao_meio_oficial.setShortcut("")
        self.botao_meio_oficial.setObjectName("botao_meio_oficial")
        self.botao_manutentor = QtWidgets.QPushButton(self.centralwidget)
        self.botao_manutentor.setGeometry(QtCore.QRect(675, 300, 249, 250))
        self.botao_manutentor.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;\n"
"font: 75 65pt \"Bosch Sans Bold\";\n"
"border-radius: 0px;\n"
"background-color: rgb(255, 255, 255);")
        self.botao_manutentor.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("imagens/Manutentor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_manutentor.setIcon(icon2)
        self.botao_manutentor.setIconSize(QtCore.QSize(240, 240))
        self.botao_manutentor.setShortcut("")
        self.botao_manutentor.setObjectName("botao_manutentor")
        self.botao_responsavel = QtWidgets.QPushButton(self.centralwidget)
        self.botao_responsavel.setGeometry(QtCore.QRect(980, 300, 249, 250))
        self.botao_responsavel.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;\n"
"font: 75 65pt \"Bosch Sans Bold\";\n"
"border-radius: 0px;\n"
"background-color: rgb(255, 255, 255);")
        self.botao_responsavel.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("imagens/Responsavel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_responsavel.setIcon(icon3)
        self.botao_responsavel.setIconSize(QtCore.QSize(240, 240))
        self.botao_responsavel.setShortcut("")
        self.botao_responsavel.setObjectName("botao_responsavel")
        cadastros_classes.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(cadastros_classes)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1290, 21))
        self.menubar.setObjectName("menubar")
        cadastros_classes.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(cadastros_classes)
        self.statusbar.setObjectName("statusbar")
        cadastros_classes.setStatusBar(self.statusbar)

        self.retranslateUi(cadastros_classes)
        QtCore.QMetaObject.connectSlotsByName(cadastros_classes)

    def retranslateUi(self, cadastros_classes):
        _translate = QtCore.QCoreApplication.translate
        cadastros_classes.setWindowTitle(_translate("cadastros_classes", "MainWindow"))
        self.label_titulo.setText(_translate("cadastros_classes", "<html><head/><body><p align=\"center\"><span style=\" font-family:\'Bosch Office Sans\'; font-size:60pt; font-weight:600; color:#000000;\">SELECIONE A CLASSE</span></p></body></html>"))
        self.botao_voltar.setWhatsThis(_translate("cadastros_classes", "<html><head/><body><p><span style=\" color:#ffffff;\">OI</span></p></body></html>"))
        self.botao_voltar.setText(_translate("cadastros_classes", "VOLTAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    cadastros_classes = QtWidgets.QMainWindow()
    ui = Ui_cadastros_classes()
    ui.setupUi(cadastros_classes)
    cadastros_classes.show()
    sys.exit(app.exec_())
