# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'documentos_diagrama_eletrico_imagens.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_documentos_diagrama_eletrico(object):
    def setupUi(self, documentos_diagrama_eletrico):
        documentos_diagrama_eletrico.setObjectName("documentos_diagrama_eletrico")
        documentos_diagrama_eletrico.resize(1290, 841)
        documentos_diagrama_eletrico.setMinimumSize(QtCore.QSize(1290, 841))
        documentos_diagrama_eletrico.setMaximumSize(QtCore.QSize(1290, 841))
        documentos_diagrama_eletrico.setStyleSheet("background-color: rgb(255, 255, 255);")
        documentos_diagrama_eletrico.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(documentos_diagrama_eletrico)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_Borda = QtWidgets.QLabel(self.centralwidget)
        self.Label_Borda.setGeometry(QtCore.QRect(0, 783, 1290, 18))
        self.Label_Borda.setText("")
        self.Label_Borda.setPixmap(QtGui.QPixmap("Imagens/Borda.png"))
        self.Label_Borda.setScaledContents(True)
        self.Label_Borda.setObjectName("Label_Borda")
        self.label_diagrama = QtWidgets.QLabel(self.centralwidget)
        self.label_diagrama.setGeometry(QtCore.QRect(40, 20, 150, 150))
        self.label_diagrama.setMinimumSize(QtCore.QSize(0, 0))
        self.label_diagrama.setStyleSheet("\n"
"border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;\n"
"font: 75 85pt \"Bosch Sans Bold\";\n"
"border-radius: 75px;\n"
"background-color: rgb(255, 207, 0);\n"
"\n"
"")
        self.label_diagrama.setText("")
        self.label_diagrama.setPixmap(QtGui.QPixmap("imagens/Diagrama_eletrico.svg"))
        self.label_diagrama.setScaledContents(False)
        self.label_diagrama.setAlignment(QtCore.Qt.AlignCenter)
        self.label_diagrama.setWordWrap(False)
        self.label_diagrama.setIndent(-1)
        self.label_diagrama.setObjectName("label_diagrama")
        self.botao_home = QtWidgets.QPushButton(self.centralwidget)
        self.botao_home.setGeometry(QtCore.QRect(1150, 10, 120, 120))
        self.botao_home.setStyleSheet("\n"
"border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;\n"
"font: 75 65pt \"Bosch Sans Bold\";\n"
"border-radius: 0px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.botao_home.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imagens/Home.Documentos.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_home.setIcon(icon)
        self.botao_home.setIconSize(QtCore.QSize(105, 105))
        self.botao_home.setObjectName("botao_home")
        self.label_imagem = QtWidgets.QLabel(self.centralwidget)
        self.label_imagem.setGeometry(QtCore.QRect(220, 40, 901, 641))
        self.label_imagem.setObjectName("label_imagem")
        self.botao_seta_direita = QtWidgets.QPushButton(self.centralwidget)
        self.botao_seta_direita.setGeometry(QtCore.QRect(1130, 650, 121, 111))
        self.botao_seta_direita.setStyleSheet("\n"
"border-style: outset/inside;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:0px;\n"
"font: 75 65pt \"Bosch Sans Bold\";\n"
"border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.botao_seta_direita.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("imagens/Seta Preta para direita.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_seta_direita.setIcon(icon1)
        self.botao_seta_direita.setIconSize(QtCore.QSize(105, 105))
        self.botao_seta_direita.setObjectName("botao_seta_direita")
        self.botao_seta_esquerda = QtWidgets.QPushButton(self.centralwidget)
        self.botao_seta_esquerda.setGeometry(QtCore.QRect(40, 650, 101, 121))
        self.botao_seta_esquerda.setStyleSheet("border-style: outset/inside;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:0px;\n"
"font: 75 65pt \"Bosch Sans Bold\";\n"
"border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.botao_seta_esquerda.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("imagens/Seta Branca para esquerda.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_seta_esquerda.setIcon(icon2)
        self.botao_seta_esquerda.setIconSize(QtCore.QSize(105, 105))
        self.botao_seta_esquerda.setObjectName("botao_seta_esquerda")
        self.label_paginas = QtWidgets.QLabel(self.centralwidget)
        self.label_paginas.setGeometry(QtCore.QRect(530, 720, 201, 41))
        self.label_paginas.setStyleSheet("font: 75 20pt \"Bosch Sans Bold\";")
        self.label_paginas.setObjectName("label_paginas")
        documentos_diagrama_eletrico.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(documentos_diagrama_eletrico)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1290, 21))
        self.menubar.setObjectName("menubar")
        documentos_diagrama_eletrico.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(documentos_diagrama_eletrico)
        self.statusbar.setObjectName("statusbar")
        documentos_diagrama_eletrico.setStatusBar(self.statusbar)

        self.retranslateUi(documentos_diagrama_eletrico)
        QtCore.QMetaObject.connectSlotsByName(documentos_diagrama_eletrico)

    def retranslateUi(self, documentos_diagrama_eletrico):
        _translate = QtCore.QCoreApplication.translate
        documentos_diagrama_eletrico.setWindowTitle(_translate("documentos_diagrama_eletrico", "MainWindow"))
        self.label_imagem.setText(_translate("documentos_diagrama_eletrico", "imagem"))
        self.label_paginas.setText(_translate("documentos_diagrama_eletrico", "PÁGINA 01/03"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    documentos_diagrama_eletrico = QtWidgets.QMainWindow()
    ui = Ui_documentos_diagrama_eletrico()
    ui.setupUi(documentos_diagrama_eletrico)
    documentos_diagrama_eletrico.show()
    sys.exit(app.exec_())
