# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Documentos_Documentos_de_pecas_menuu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_documentos_documentos_de_pecas_menu(object):
    def setupUi(self, documentos_documentos_de_pecas_menu):
        documentos_documentos_de_pecas_menu.setObjectName("documentos_documentos_de_pecas_menu")
        documentos_documentos_de_pecas_menu.resize(1290, 841)
        documentos_documentos_de_pecas_menu.setMinimumSize(QtCore.QSize(1290, 841))
        documentos_documentos_de_pecas_menu.setMaximumSize(QtCore.QSize(1290, 841))
        documentos_documentos_de_pecas_menu.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(documentos_documentos_de_pecas_menu)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_Borda = QtWidgets.QLabel(self.centralwidget)
        self.Label_Borda.setGeometry(QtCore.QRect(0, 783, 1290, 18))
        self.Label_Borda.setText("")
        self.Label_Borda.setPixmap(QtGui.QPixmap("Imagens/Borda.png"))
        self.Label_Borda.setScaledContents(True)
        self.Label_Borda.setObjectName("Label_Borda")
        self.botao_peca01_2 = QtWidgets.QPushButton(self.centralwidget)
        self.botao_peca01_2.setGeometry(QtCore.QRect(330, 96, 761, 155))
        self.botao_peca01_2.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(234, 229, 239);\n"
"border-width:7px;\n"
"font: 75 50pt \"Bosch Sans Bold\";\n"
"border-radius: 30px;")
        self.botao_peca01_2.setObjectName("botao_peca01_2")
        self.imagem = QtWidgets.QPushButton(self.centralwidget)
        self.imagem.setGeometry(QtCore.QRect(40, 20, 151, 151))
        self.imagem.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(155, 228, 179);\n"
"border-width:7px;\n"
"border-radius: 75px;\n"
"font: 75 50pt \"Bosch Sans Bold\";")
        self.imagem.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imagens/Documentos.Peças.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.imagem.setIcon(icon)
        self.imagem.setIconSize(QtCore.QSize(100, 100))
        self.imagem.setObjectName("imagem")
        self.botao_home = QtWidgets.QPushButton(self.centralwidget)
        self.botao_home.setGeometry(QtCore.QRect(1150, 10, 120, 120))
        self.botao_home.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;")
        self.botao_home.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("imagens/Home.Documentos.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_home.setIcon(icon1)
        self.botao_home.setIconSize(QtCore.QSize(105, 105))
        self.botao_home.setObjectName("botao_home")
        self.botao_peca01_1 = QtWidgets.QPushButton(self.centralwidget)
        self.botao_peca01_1.setGeometry(QtCore.QRect(220, 83, 181, 181))
        self.botao_peca01_1.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(155, 228, 179);\n"
"border-width:7px;\n"
"border-radius: 90px;\n"
"font: 75 95pt \"Bosch Sans Bold\";")
        self.botao_peca01_1.setObjectName("botao_peca01_1")
        self.botao_peca02_1 = QtWidgets.QPushButton(self.centralwidget)
        self.botao_peca02_1.setGeometry(QtCore.QRect(230, 313, 181, 181))
        self.botao_peca02_1.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(155, 228, 179);\n"
"border-width:7px;\n"
"border-radius: 90px;\n"
"font: 75 95pt \"Bosch Sans Bold\";")
        self.botao_peca02_1.setObjectName("botao_peca02_1")
        self.botao_peca02_2 = QtWidgets.QPushButton(self.centralwidget)
        self.botao_peca02_2.setGeometry(QtCore.QRect(340, 323, 761, 155))
        self.botao_peca02_2.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(234, 229, 239);\n"
"border-width:7px;\n"
"font: 75 50pt \"Bosch Sans Bold\";\n"
"border-radius: 30px;")
        self.botao_peca02_2.setObjectName("botao_peca02_2")
        self.botao_peca03_1 = QtWidgets.QPushButton(self.centralwidget)
        self.botao_peca03_1.setGeometry(QtCore.QRect(220, 550, 181, 181))
        self.botao_peca03_1.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(155, 228, 179);\n"
"border-width:7px;\n"
"border-radius: 90px;\n"
"font: 75 95pt \"Bosch Sans Bold\";")
        self.botao_peca03_1.setObjectName("botao_peca03_1")
        self.botao_peca03_2 = QtWidgets.QPushButton(self.centralwidget)
        self.botao_peca03_2.setGeometry(QtCore.QRect(330, 563, 761, 155))
        self.botao_peca03_2.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(234, 229, 239);\n"
"border-width:7px;\n"
"font: 75 50pt \"Bosch Sans Bold\";\n"
"border-radius: 30px;")
        self.botao_peca03_2.setObjectName("botao_peca03_2")
        self.Label_Borda.raise_()
        self.botao_peca01_2.raise_()
        self.imagem.raise_()
        self.botao_home.raise_()
        self.botao_peca01_1.raise_()
        self.botao_peca02_2.raise_()
        self.botao_peca02_1.raise_()
        self.botao_peca03_2.raise_()
        self.botao_peca03_1.raise_()
        documentos_documentos_de_pecas_menu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(documentos_documentos_de_pecas_menu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1290, 21))
        self.menubar.setObjectName("menubar")
        documentos_documentos_de_pecas_menu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(documentos_documentos_de_pecas_menu)
        self.statusbar.setObjectName("statusbar")
        documentos_documentos_de_pecas_menu.setStatusBar(self.statusbar)

        self.retranslateUi(documentos_documentos_de_pecas_menu)
        QtCore.QMetaObject.connectSlotsByName(documentos_documentos_de_pecas_menu)

    def retranslateUi(self, documentos_documentos_de_pecas_menu):
        _translate = QtCore.QCoreApplication.translate
        documentos_documentos_de_pecas_menu.setWindowTitle(_translate("documentos_documentos_de_pecas_menu", "MainWindow"))
        self.botao_peca01_2.setText(_translate("documentos_documentos_de_pecas_menu", "PEÇA 01"))
        self.botao_peca01_1.setText(_translate("documentos_documentos_de_pecas_menu", "1"))
        self.botao_peca02_1.setText(_translate("documentos_documentos_de_pecas_menu", "2"))
        self.botao_peca02_2.setText(_translate("documentos_documentos_de_pecas_menu", "PEÇA 02"))
        self.botao_peca03_1.setText(_translate("documentos_documentos_de_pecas_menu", "3"))
        self.botao_peca03_2.setText(_translate("documentos_documentos_de_pecas_menu", "PEÇA 03"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    documentos_documentos_de_pecas_menu = QtWidgets.QMainWindow()
    ui = Ui_documentos_documentos_de_pecas_menu()
    ui.setupUi(documentos_documentos_de_pecas_menu)
    documentos_documentos_de_pecas_menu.show()
    sys.exit(app.exec_())
