# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'documentos_documentos_de_pecas_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_peca02(object):
    def setupUi(self, peca02):
        peca02.setObjectName("peca02")
        peca02.resize(1290, 841)
        peca02.setMinimumSize(QtCore.QSize(1290, 841))
        peca02.setMaximumSize(QtCore.QSize(1290, 841))
        peca02.setStyleSheet("background-color: rgb(255, 255, 255);")
        peca02.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(peca02)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_Borda = QtWidgets.QLabel(self.centralwidget)
        self.Label_Borda.setGeometry(QtCore.QRect(0, 783, 1290, 18))
        self.Label_Borda.setText("")
        self.Label_Borda.setPixmap(QtGui.QPixmap("Imagens/Borda.png"))
        self.Label_Borda.setScaledContents(True)
        self.Label_Borda.setObjectName("Label_Borda")
        self.label_numero_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_numero_2.setGeometry(QtCore.QRect(40, 30, 150, 150))
        self.label_numero_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_numero_2.setStyleSheet("\n"
"border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;\n"
"font: 75 85pt \"Bosch Sans Bold\";\n"
"border-radius: 75px;\n"
"background-color: rgb(155, 228, 179);\n"
"\n"
"")
        self.label_numero_2.setScaledContents(False)
        self.label_numero_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_numero_2.setWordWrap(False)
        self.label_numero_2.setIndent(-1)
        self.label_numero_2.setObjectName("label_numero_2")
        self.botao_home = QtWidgets.QPushButton(self.centralwidget)
        self.botao_home.setGeometry(QtCore.QRect(1150, 10, 120, 120))
        self.botao_home.setStyleSheet("\n"
"border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;\n"
"font: 75 65pt \"Bosch Sans Bold\";\n"
"border-radius: 0px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.botao_home.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imagens/Home.Documentos.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_home.setIcon(icon)
        self.botao_home.setIconSize(QtCore.QSize(105, 105))
        self.botao_home.setObjectName("botao_home")
        self.label_imagem = QtWidgets.QLabel(self.centralwidget)
        self.label_imagem.setGeometry(QtCore.QRect(560, 320, 121, 111))
        self.label_imagem.setObjectName("label_imagem")
        peca02.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(peca02)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1290, 21))
        self.menubar.setObjectName("menubar")
        peca02.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(peca02)
        self.statusbar.setObjectName("statusbar")
        peca02.setStatusBar(self.statusbar)

        self.retranslateUi(peca02)
        QtCore.QMetaObject.connectSlotsByName(peca02)

    def retranslateUi(self, peca02):
        _translate = QtCore.QCoreApplication.translate
        peca02.setWindowTitle(_translate("peca02", "MainWindow"))
        self.label_numero_2.setText(_translate("peca02", "2"))
        self.label_imagem.setText(_translate("peca02", "imagem"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    peca02 = QtWidgets.QMainWindow()
    ui = Ui_peca02()
    ui.setupUi(peca02)
    peca02.show()
    sys.exit(app.exec_())
