# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface_didatica_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_interface_didatica_menu(object):
    def setupUi(self, interface_didatica_menu):
        interface_didatica_menu.setObjectName("interface_didatica_menu")
        interface_didatica_menu.resize(1290, 841)
        interface_didatica_menu.setMinimumSize(QtCore.QSize(1290, 841))
        interface_didatica_menu.setMaximumSize(QtCore.QSize(1290, 841))
        interface_didatica_menu.setStyleSheet("background-color: rgb(255, 255, 255);")
        interface_didatica_menu.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(interface_didatica_menu)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_Borda = QtWidgets.QLabel(self.centralwidget)
        self.Label_Borda.setGeometry(QtCore.QRect(0, 783, 1290, 18))
        self.Label_Borda.setText("")
        self.Label_Borda.setPixmap(QtGui.QPixmap("Imagens/Borda.png"))
        self.Label_Borda.setScaledContents(True)
        self.Label_Borda.setObjectName("Label_Borda")
        self.botao_home = QtWidgets.QPushButton(self.centralwidget)
        self.botao_home.setGeometry(QtCore.QRect(1080, 30, 141, 141))
        self.botao_home.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;\n"
"font: 75 65pt \"Bosch Sans Bold\";\n"
"border-radius: 70px;\n"
"background-color: rgb(255, 255, 255);")
        self.botao_home.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imagens/Home.Interface.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_home.setIcon(icon)
        self.botao_home.setIconSize(QtCore.QSize(99, 99))
        self.botao_home.setObjectName("botao_home")
        self.label_caixa_roxa = QtWidgets.QLabel(self.centralwidget)
        self.label_caixa_roxa.setGeometry(QtCore.QRect(20, 0, 1241, 761))
        font = QtGui.QFont()
        font.setFamily("Bosch Sans Bold")
        font.setPointSize(65)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_caixa_roxa.setFont(font)
        self.label_caixa_roxa.setStyleSheet("border-style: outset;\n"
"border-color: rgb(63, 19, 108);\n"
"border-width:7px;\n"
"font: 75 65pt \"Bosch Sans Bold\";\n"
"border-radius: 85px;\n"
"background-color: rgb(178, 125, 232);")
        self.label_caixa_roxa.setText("")
        self.label_caixa_roxa.setObjectName("label_caixa_roxa")
        self.label_serra_de_perfil = QtWidgets.QLabel(self.centralwidget)
        self.label_serra_de_perfil.setGeometry(QtCore.QRect(170, 50, 871, 101))
        self.label_serra_de_perfil.setStyleSheet("border-style: outset/inside;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:0px;\n"
"font: 75 70pt \"Bosch Sans Bold\";\n"
"border-radius: 15px;\n"
"background-color: rgb(178, 125, 232);")
        self.label_serra_de_perfil.setObjectName("label_serra_de_perfil")
        self.botao_botoes = QtWidgets.QPushButton(self.centralwidget)
        self.botao_botoes.setGeometry(QtCore.QRect(580, 250, 651, 120))
        self.botao_botoes.setMinimumSize(QtCore.QSize(100, 0))
        self.botao_botoes.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;\n"
"font: 75 45pt \"Bosch Sans Bold\";\n"
"border-radius: 15px;\n"
"background-color: rgb(234, 229, 239);")
        self.botao_botoes.setObjectName("botao_botoes")
        self.botao_finalidades = QtWidgets.QPushButton(self.centralwidget)
        self.botao_finalidades.setGeometry(QtCore.QRect(580, 420, 651, 120))
        self.botao_finalidades.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;\n"
"font: 75 45pt \"Bosch Sans Bold\";\n"
"border-radius: 15px;\n"
"background-color: rgb(234, 229, 239);")
        self.botao_finalidades.setShortcut("")
        self.botao_finalidades.setObjectName("botao_finalidades")
        self.botao_modo_de_utilizar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_modo_de_utilizar.setGeometry(QtCore.QRect(580, 590, 651, 120))
        self.botao_modo_de_utilizar.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;\n"
"font: 75 45pt \"Bosch Sans Bold\";\n"
"border-radius: 15px;\n"
"background-color: rgb(234, 229, 239);")
        self.botao_modo_de_utilizar.setObjectName("botao_modo_de_utilizar")
        self.botao_imagem = QtWidgets.QPushButton(self.centralwidget)
        self.botao_imagem.setGeometry(QtCore.QRect(60, 240, 501, 481))
        self.botao_imagem.setStyleSheet("border-style: outset;\n"
"border-color: rgb(63, 19, 108);\n"
"border-width:7px;\n"
"\n"
"border-radius: 70px;\n"
"background-color: rgb(255, 255, 255);")
        self.botao_imagem.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("imagens/Interface.Serra_de_Perfil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_imagem.setIcon(icon1)
        self.botao_imagem.setIconSize(QtCore.QSize(400, 400))
        self.botao_imagem.setObjectName("botao_imagem")
        self.Label_Borda.raise_()
        self.label_caixa_roxa.raise_()
        self.botao_home.raise_()
        self.label_serra_de_perfil.raise_()
        self.botao_botoes.raise_()
        self.botao_finalidades.raise_()
        self.botao_modo_de_utilizar.raise_()
        self.botao_imagem.raise_()
        interface_didatica_menu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(interface_didatica_menu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1290, 21))
        self.menubar.setObjectName("menubar")
        interface_didatica_menu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(interface_didatica_menu)
        self.statusbar.setObjectName("statusbar")
        interface_didatica_menu.setStatusBar(self.statusbar)

        self.retranslateUi(interface_didatica_menu)
        QtCore.QMetaObject.connectSlotsByName(interface_didatica_menu)

    def retranslateUi(self, interface_didatica_menu):
        _translate = QtCore.QCoreApplication.translate
        interface_didatica_menu.setWindowTitle(_translate("interface_didatica_menu", "MainWindow"))
        self.label_serra_de_perfil.setText(_translate("interface_didatica_menu", "SERRA DE PERFIL"))
        self.botao_botoes.setText(_translate("interface_didatica_menu", "BOTÕES                    "))
        self.botao_finalidades.setText(_translate("interface_didatica_menu", "FINALIDADE             "))
        self.botao_modo_de_utilizar.setText(_translate("interface_didatica_menu", "MODO DE UTILIZAR "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    interface_didatica_menu = QtWidgets.QMainWindow()
    ui = Ui_interface_didatica_menu()
    ui.setupUi(interface_didatica_menu)
    interface_didatica_menu.show()
    sys.exit(app.exec_())
