# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface_didatica_finalidade.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_interface_didatica_finalidade(object):
    def setupUi(self, interface_didatica_finalidade):
        interface_didatica_finalidade.setObjectName("interface_didatica_finalidade")
        interface_didatica_finalidade.resize(1290, 841)
        interface_didatica_finalidade.setMinimumSize(QtCore.QSize(1290, 841))
        interface_didatica_finalidade.setMaximumSize(QtCore.QSize(1290, 841))
        interface_didatica_finalidade.setStyleSheet("background-color: rgb(255, 255, 255);")
        interface_didatica_finalidade.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(interface_didatica_finalidade)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_Borda = QtWidgets.QLabel(self.centralwidget)
        self.Label_Borda.setGeometry(QtCore.QRect(0, 783, 1290, 18))
        self.Label_Borda.setText("")
        self.Label_Borda.setPixmap(QtGui.QPixmap("Imagens/Borda.png"))
        self.Label_Borda.setScaledContents(True)
        self.Label_Borda.setObjectName("Label_Borda")
        self.botao_home = QtWidgets.QPushButton(self.centralwidget)
        self.botao_home.setGeometry(QtCore.QRect(1120, 0, 141, 141))
        self.botao_home.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:6px;\n"
"font: 75 65pt \"Bosch Sans Bold\";\n"
"\n"
"background-color: rgb(255, 255, 255);")
        self.botao_home.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imagens/Home.Interface.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_home.setIcon(icon)
        self.botao_home.setIconSize(QtCore.QSize(99, 99))
        self.botao_home.setObjectName("botao_home")
        self.label_fundo = QtWidgets.QLabel(self.centralwidget)
        self.label_fundo.setGeometry(QtCore.QRect(20, 0, 1241, 761))
        font = QtGui.QFont()
        font.setFamily("Bosch Sans Bold")
        font.setPointSize(65)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_fundo.setFont(font)
        self.label_fundo.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:7px;\n"
"font: 75 65pt \"Bosch Sans Bold\";\n"
"\n"
"background-color: rgb(138, 144, 151);")
        self.label_fundo.setObjectName("label_fundo")
        self.label_serra_de_perfil = QtWidgets.QLabel(self.centralwidget)
        self.label_serra_de_perfil.setGeometry(QtCore.QRect(20, 0, 1110, 141))
        self.label_serra_de_perfil.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:6px;\n"
"font: 75 70pt \"Bosch Sans Bold\";\n"
"\n"
"background-color: rgb(237, 0, 7);")
        self.label_serra_de_perfil.setObjectName("label_serra_de_perfil")
        self.label_texto = QtWidgets.QLabel(self.centralwidget)
        self.label_texto.setGeometry(QtCore.QRect(60, 180, 591, 541))
        self.label_texto.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;\n"
"font: 75 20pt \"Bosch Sans Bold\";\n"
"border-radius: 70px;\n"
"background-color: rgb(193, 199, 204);")
        self.label_texto.setObjectName("label_texto")
        self.label_imagem = QtWidgets.QLabel(self.centralwidget)
        self.label_imagem.setGeometry(QtCore.QRect(680, 260, 541, 371))
        self.label_imagem.setStyleSheet("\n"
"font: 75 18pt \"Bosch Sans Bold\";\n"
"\n"
"background-color: rgb(193, 199, 204);")
        self.label_imagem.setText("")
        self.label_imagem.setPixmap(QtGui.QPixmap("imagens/perfis_de_aluminio.png"))
        self.label_imagem.setScaledContents(True)
        self.label_imagem.setObjectName("label_imagem")
        self.Label_Borda.raise_()
        self.label_fundo.raise_()
        self.botao_home.raise_()
        self.label_serra_de_perfil.raise_()
        self.label_texto.raise_()
        self.label_imagem.raise_()
        interface_didatica_finalidade.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(interface_didatica_finalidade)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1290, 21))
        self.menubar.setObjectName("menubar")
        interface_didatica_finalidade.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(interface_didatica_finalidade)
        self.statusbar.setObjectName("statusbar")
        interface_didatica_finalidade.setStatusBar(self.statusbar)

        self.retranslateUi(interface_didatica_finalidade)
        QtCore.QMetaObject.connectSlotsByName(interface_didatica_finalidade)

    def retranslateUi(self, interface_didatica_finalidade):
        _translate = QtCore.QCoreApplication.translate
        interface_didatica_finalidade.setWindowTitle(_translate("interface_didatica_finalidade", "MainWindow"))
        self.label_serra_de_perfil.setText(_translate("interface_didatica_finalidade", "   SERRA DE PERFIL"))
        self.label_texto.setText(_translate("interface_didatica_finalidade", "    Sua principal função é de cortar perfis \n"
"de alumínio. Através de seu sistema \n"
"operacional e automático, fornece um \n"
"corte seguro evitando acidentes e \n"
"garantindo precisão no local de corte.\n"
"    Ela também pode ser utilizada para \n"
"cortar outros tipos de materiais, porém \n"
"esta possui uso restrito para perfis \n"
"de alumínio.\n"
""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    interface_didatica_finalidade = QtWidgets.QMainWindow()
    ui = Ui_interface_didatica_finalidade()
    ui.setupUi(interface_didatica_finalidade)
    interface_didatica_finalidade.show()
    sys.exit(app.exec_())
