# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface_didatica_menu_botoes_botoeira.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_interface_didatica_menu_botoes(object):
    def setupUi(self, interface_didatica_menu_botoes):
        interface_didatica_menu_botoes.setObjectName("interface_didatica_menu_botoes")
        interface_didatica_menu_botoes.resize(1290, 841)
        interface_didatica_menu_botoes.setMinimumSize(QtCore.QSize(1290, 841))
        interface_didatica_menu_botoes.setMaximumSize(QtCore.QSize(1290, 841))
        interface_didatica_menu_botoes.setStyleSheet("background-color: rgb(255, 255, 255);")
        interface_didatica_menu_botoes.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(interface_didatica_menu_botoes)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_Borda = QtWidgets.QLabel(self.centralwidget)
        self.Label_Borda.setGeometry(QtCore.QRect(0, 783, 1290, 18))
        self.Label_Borda.setText("")
        self.Label_Borda.setPixmap(QtGui.QPixmap("Imagens/Borda.png"))
        self.Label_Borda.setScaledContents(True)
        self.Label_Borda.setObjectName("Label_Borda")
        self.botao_home = QtWidgets.QPushButton(self.centralwidget)
        self.botao_home.setGeometry(QtCore.QRect(1080, 30, 141, 141))
        self.botao_home.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;\n"
"font: 75 65pt \"Bosch Sans Bold\";\n"
"border-radius: 70px;\n"
"background-color: rgb(255, 255, 255);")
        self.botao_home.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imagens/Home.Interface.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_home.setIcon(icon)
        self.botao_home.setIconSize(QtCore.QSize(99, 99))
        self.botao_home.setObjectName("botao_home")
        self.label_fundo = QtWidgets.QLabel(self.centralwidget)
        self.label_fundo.setGeometry(QtCore.QRect(20, 0, 1241, 761))
        font = QtGui.QFont()
        font.setFamily("Bosch Sans Bold")
        font.setPointSize(65)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_fundo.setFont(font)
        self.label_fundo.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:7px;\n"
"border-radius: 85px;\n"
"background-color: rgb(193, 199, 204);")
        self.label_fundo.setText("")
        self.label_fundo.setObjectName("label_fundo")
        self.label_quadrado_da_imagem = QtWidgets.QLabel(self.centralwidget)
        self.label_quadrado_da_imagem.setGeometry(QtCore.QRect(70, 40, 941, 351))
        self.label_quadrado_da_imagem.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:6px;\n"
"\n"
"\n"
"font: 75 80pt \"Bosch Sans Bold\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_quadrado_da_imagem.setText("")
        self.label_quadrado_da_imagem.setPixmap(QtGui.QPixmap("imagens/botoeira.jpg"))
        self.label_quadrado_da_imagem.setScaledContents(True)
        self.label_quadrado_da_imagem.setObjectName("label_quadrado_da_imagem")
        self.label_caixa_maior = QtWidgets.QLabel(self.centralwidget)
        self.label_caixa_maior.setGeometry(QtCore.QRect(70, 410, 941, 301))
        self.label_caixa_maior.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:6px;\n"
"\n"
"\n"
"\n"
"background-color: rgb(255, 255, 255);")
        self.label_caixa_maior.setText("")
        self.label_caixa_maior.setObjectName("label_caixa_maior")
        self.label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo.setGeometry(QtCore.QRect(194, 410, 811, 81))
        self.label_titulo.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:6px;\n"
"\n"
"\n"
"font: 75 35pt \"Bosch Sans Bold\";\n"
"background-color: rgb(0,0,0);")
        self.label_titulo.setObjectName("label_titulo")
        self.label_indicacao = QtWidgets.QLabel(self.centralwidget)
        self.label_indicacao.setGeometry(QtCore.QRect(70, 410, 131, 141))
        self.label_indicacao.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:6px;\n"
"background-color: rgb(155, 228, 179);\n"
"\n"
"font: 75 80pt \"Bosch Sans Bold\";\n"
"")
        self.label_indicacao.setText("")
        self.label_indicacao.setPixmap(QtGui.QPixmap("imagens/maozinha_interface.png"))
        self.label_indicacao.setScaledContents(True)
        self.label_indicacao.setObjectName("label_indicacao")
        self.label_caixa_de_texto = QtWidgets.QLabel(self.centralwidget)
        self.label_caixa_de_texto.setGeometry(QtCore.QRect(80, 500, 921, 191))
        self.label_caixa_de_texto.setStyleSheet("font: 75 24pt \"Bosch Sans Bold\";\n"
"\n"
"")
        self.label_caixa_de_texto.setObjectName("label_caixa_de_texto")
        self.botao_1 = QtWidgets.QPushButton(self.centralwidget)
        self.botao_1.setGeometry(QtCore.QRect(160, 290, 91, 91))
        self.botao_1.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0,0,0);\n"
"background-color: rgb(155, 228, 179);\n"
"border-width:5px;\n"
"font: 75 49pt \"Bosch Sans Bold\";\n"
"border-radius: 45px;\n"
"")
        self.botao_1.setObjectName("botao_1")
        self.botao_2 = QtWidgets.QPushButton(self.centralwidget)
        self.botao_2.setGeometry(QtCore.QRect(320, 290, 91, 91))
        self.botao_2.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0,0,0);\n"
"background-color: rgb(155, 228, 179);\n"
"border-width:5px;\n"
"font: 75 49pt \"Bosch Sans Bold\";\n"
"border-radius: 45px;\n"
"")
        self.botao_2.setObjectName("botao_2")
        self.botao_3 = QtWidgets.QPushButton(self.centralwidget)
        self.botao_3.setGeometry(QtCore.QRect(480, 290, 91, 91))
        self.botao_3.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0,0,0);\n"
"background-color: rgb(155, 228, 179);\n"
"border-width:5px;\n"
"font: 75 49pt \"Bosch Sans Bold\";\n"
"border-radius: 45px;\n"
"")
        self.botao_3.setObjectName("botao_3")
        self.botao_4 = QtWidgets.QPushButton(self.centralwidget)
        self.botao_4.setGeometry(QtCore.QRect(640, 290, 91, 91))
        self.botao_4.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0,0,0);\n"
"background-color: rgb(155, 228, 179);\n"
"border-width:5px;\n"
"font: 75 49pt \"Bosch Sans Bold\";\n"
"border-radius: 45px;\n"
"")
        self.botao_4.setObjectName("botao_4")
        self.botao_5 = QtWidgets.QPushButton(self.centralwidget)
        self.botao_5.setGeometry(QtCore.QRect(810, 290, 91, 91))
        self.botao_5.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0,0,0);\n"
"background-color: rgb(155, 228, 179);\n"
"border-width:5px;\n"
"font: 75 49pt \"Bosch Sans Bold\";\n"
"border-radius: 45px;\n"
"")
        self.botao_5.setObjectName("botao_5")
        self.botao_seta_esquerda = QtWidgets.QPushButton(self.centralwidget)
        self.botao_seta_esquerda.setGeometry(QtCore.QRect(1030, 570, 98, 117))
        self.botao_seta_esquerda.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0,0,0);\n"
"\n"
"")
        self.botao_seta_esquerda.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("imagens/seta_esquerda_cinza_interface_botoes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_seta_esquerda.setIcon(icon1)
        self.botao_seta_esquerda.setIconSize(QtCore.QSize(120, 120))
        self.botao_seta_esquerda.setShortcut("")
        self.botao_seta_esquerda.setObjectName("botao_seta_esquerda")
        self.botao_seta_dirteita = QtWidgets.QPushButton(self.centralwidget)
        self.botao_seta_dirteita.setGeometry(QtCore.QRect(1140, 570, 96, 115))
        self.botao_seta_dirteita.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0,0,0);\n"
"\n"
"")
        self.botao_seta_dirteita.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("imagens/Seta_cinza Preta para direita.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_seta_dirteita.setIcon(icon2)
        self.botao_seta_dirteita.setIconSize(QtCore.QSize(120, 120))
        self.botao_seta_dirteita.setShortcut("")
        self.botao_seta_dirteita.setObjectName("botao_seta_dirteita")
        self.Label_Borda.raise_()
        self.label_fundo.raise_()
        self.botao_home.raise_()
        self.label_quadrado_da_imagem.raise_()
        self.label_caixa_maior.raise_()
        self.label_titulo.raise_()
        self.label_caixa_de_texto.raise_()
        self.label_indicacao.raise_()
        self.botao_1.raise_()
        self.botao_2.raise_()
        self.botao_3.raise_()
        self.botao_4.raise_()
        self.botao_5.raise_()
        self.botao_seta_esquerda.raise_()
        self.botao_seta_dirteita.raise_()
        interface_didatica_menu_botoes.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(interface_didatica_menu_botoes)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1290, 21))
        self.menubar.setObjectName("menubar")
        interface_didatica_menu_botoes.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(interface_didatica_menu_botoes)
        self.statusbar.setObjectName("statusbar")
        interface_didatica_menu_botoes.setStatusBar(self.statusbar)

        self.retranslateUi(interface_didatica_menu_botoes)
        QtCore.QMetaObject.connectSlotsByName(interface_didatica_menu_botoes)

    def retranslateUi(self, interface_didatica_menu_botoes):
        _translate = QtCore.QCoreApplication.translate
        interface_didatica_menu_botoes.setWindowTitle(_translate("interface_didatica_menu_botoes", "MainWindow"))
        self.label_titulo.setText(_translate("interface_didatica_menu_botoes", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">BOTOEIRA</span></p></body></html>"))
        self.label_caixa_de_texto.setText(_translate("interface_didatica_menu_botoes", "             Clique nos números para verificar a respectiva \n"
"função do botão ou chave seletora. \n"
" \n"
""))
        self.botao_1.setText(_translate("interface_didatica_menu_botoes", "1"))
        self.botao_2.setText(_translate("interface_didatica_menu_botoes", "2"))
        self.botao_3.setText(_translate("interface_didatica_menu_botoes", "3"))
        self.botao_4.setText(_translate("interface_didatica_menu_botoes", "4"))
        self.botao_5.setText(_translate("interface_didatica_menu_botoes", "5"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    interface_didatica_menu_botoes = QtWidgets.QMainWindow()
    ui = Ui_interface_didatica_menu_botoes()
    ui.setupUi(interface_didatica_menu_botoes)
    interface_didatica_menu_botoes.show()
    sys.exit(app.exec_())
