# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'leitor.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_leitor(object):
    def setupUi(self, leitor):
        leitor.setObjectName("leitor")
        leitor.resize(1290, 841)
        leitor.setMinimumSize(QtCore.QSize(1290, 841))
        leitor.setMaximumSize(QtCore.QSize(1290, 841))
        leitor.setStyleSheet("background-color: rgb(255, 255, 255);")
        leitor.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(leitor)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_Borda = QtWidgets.QLabel(self.centralwidget)
        self.Label_Borda.setGeometry(QtCore.QRect(0, 783, 1290, 18))
        self.Label_Borda.setText("")
        self.Label_Borda.setPixmap(QtGui.QPixmap("Imagens/Borda.png"))
        self.Label_Borda.setScaledContents(True)
        self.Label_Borda.setObjectName("Label_Borda")
        self.label_fundo = QtWidgets.QLabel(self.centralwidget)
        self.label_fundo.setGeometry(QtCore.QRect(20, 10, 1251, 761))
        font = QtGui.QFont()
        font.setFamily("Bosch Sans Bold")
        font.setPointSize(65)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_fundo.setFont(font)
        self.label_fundo.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:7px;\n"
"border-radius: 0px;\n"
"background-color: rgb(224, 227, 229);\n"
"background-color: rgb(0, 0, 0);")
        self.label_fundo.setText("")
        self.label_fundo.setObjectName("label_fundo")
        self.botao_avancar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_avancar.setGeometry(QtCore.QRect(450, 500, 361, 201))
        self.botao_avancar.setStyleSheet("border-style: outset;\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:6px;\n"
"border-radius: 30px;\n"
"\n"
"font: 75 35pt \"Bosch Sans Bold\";\n"
"background-color: rgb(255, 255, 0);")
        self.botao_avancar.setObjectName("botao_avancar")
        self.lineEdit_tag = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_tag.setGeometry(QtCore.QRect(190, 170, 851, 241))
        self.lineEdit_tag.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:6px;\n"
"background-color: rgb(193, 194, 204);\n"
"\n"
"font: 75 35pt \"Bosch Sans Bold\";\n"
"")
        self.lineEdit_tag.setObjectName("lineEdit_tag")
        leitor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(leitor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1290, 21))
        self.menubar.setObjectName("menubar")
        leitor.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(leitor)
        self.statusbar.setObjectName("statusbar")
        leitor.setStatusBar(self.statusbar)

        self.retranslateUi(leitor)
        QtCore.QMetaObject.connectSlotsByName(leitor)

    def retranslateUi(self, leitor):
        _translate = QtCore.QCoreApplication.translate
        leitor.setWindowTitle(_translate("leitor", "MainWindow"))
        self.botao_avancar.setWhatsThis(_translate("leitor", "<html><head/><body><p><span style=\" color:#ffffff;\">OI</span></p></body></html>"))
        self.botao_avancar.setText(_translate("leitor", "AVANÇAR"))
        self.lineEdit_tag.setText(_translate("leitor", "               TAG DO CARTÃO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    leitor = QtWidgets.QMainWindow()
    ui = Ui_leitor()
    ui.setupUi(leitor)
    leitor.show()
    sys.exit(app.exec_())
