# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Liberação_Meio_Ambiente.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Liberacao_Meio_Ambiente(object):
    def setupUi(self, Liberacao_Meio_Ambiente):
        Liberacao_Meio_Ambiente.setObjectName("Liberacao_Meio_Ambiente")
        Liberacao_Meio_Ambiente.resize(1290, 841)
        Liberacao_Meio_Ambiente.setMinimumSize(QtCore.QSize(1290, 841))
        Liberacao_Meio_Ambiente.setMaximumSize(QtCore.QSize(1290, 841))
        Liberacao_Meio_Ambiente.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(Liberacao_Meio_Ambiente)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_Borda = QtWidgets.QLabel(self.centralwidget)
        self.Label_Borda.setGeometry(QtCore.QRect(0, 783, 1290, 18))
        self.Label_Borda.setText("")
        self.Label_Borda.setPixmap(QtGui.QPixmap("Imagens/Borda.png"))
        self.Label_Borda.setScaledContents(True)
        self.Label_Borda.setObjectName("Label_Borda")
        self.Frame = QtWidgets.QFrame(self.centralwidget)
        self.Frame.setGeometry(QtCore.QRect(10, 10, 1270, 760))
        self.Frame.setStyleSheet("background-color: rgb(155, 228, 179);\n"
"border-style: outset;\n"
"\n"
"\n"
"\n"
"\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:6px;\n"
"")
        self.Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame.setObjectName("Frame")
        self.Label_Seguranca = QtWidgets.QLabel(self.Frame)
        self.Label_Seguranca.setGeometry(QtCore.QRect(210, 10, 841, 121))
        self.Label_Seguranca.setStyleSheet("border-style: outset;\n"
"\n"
"\n"
"\n"
"\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:0px;\n"
"\n"
"font: 75 65pt \"Bosch Sans Bold\";")
        self.Label_Seguranca.setObjectName("Label_Seguranca")
        self.checkBox_1 = QtWidgets.QCheckBox(self.Frame)
        self.checkBox_1.setGeometry(QtCore.QRect(60, 210, 641, 91))
        self.checkBox_1.setStyleSheet("\n"
"\n"
"\n"
"QCheckBox::indicator\n"
"{\n"
"width : 37px;\n"
"height : 37px;\n"
"background-color:white;\n"
"border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:3px;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"   background-color:rgb(255, 207, 0);\n"
"}\n"
"\n"
"border-style: inside;\n"
"\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:0px;\n"
"font: 75 25pt \"Bosch Sans Bold\";")
        self.checkBox_1.setObjectName("checkBox_1")
        self.botao_continuar = QtWidgets.QPushButton(self.Frame)
        self.botao_continuar.setGeometry(QtCore.QRect(890, 580, 321, 141))
        self.botao_continuar.setStyleSheet("background-color: rgb(255, 207, 0);\n"
"border-style: outset;\n"
"border-radius: 35px;\n"
"\n"
"\n"
"\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:4px;\n"
"\n"
"font: 75 35pt \"Bosch Sans Bold\";")
        self.botao_continuar.setObjectName("botao_continuar")
        self.Label_titulo = QtWidgets.QLabel(self.Frame)
        self.Label_titulo.setGeometry(QtCore.QRect(60, 140, 1021, 51))
        self.Label_titulo.setStyleSheet("border-style: outset;\n"
"\n"
"\n"
"\n"
"\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:0px;\n"
"\n"
"font: 75 25pt \"Bosch Sans Bold\";")
        self.Label_titulo.setObjectName("Label_titulo")
        self.botao_home = QtWidgets.QPushButton(self.Frame)
        self.botao_home.setGeometry(QtCore.QRect(1150, 0, 120, 120))
        self.botao_home.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;")
        self.botao_home.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imagens/Home.Liberacao.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_home.setIcon(icon)
        self.botao_home.setIconSize(QtCore.QSize(105, 105))
        self.botao_home.setObjectName("botao_home")
        Liberacao_Meio_Ambiente.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Liberacao_Meio_Ambiente)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1290, 21))
        self.menubar.setObjectName("menubar")
        Liberacao_Meio_Ambiente.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Liberacao_Meio_Ambiente)
        self.statusbar.setObjectName("statusbar")
        Liberacao_Meio_Ambiente.setStatusBar(self.statusbar)

        self.retranslateUi(Liberacao_Meio_Ambiente)
        QtCore.QMetaObject.connectSlotsByName(Liberacao_Meio_Ambiente)

    def retranslateUi(self, Liberacao_Meio_Ambiente):
        _translate = QtCore.QCoreApplication.translate
        Liberacao_Meio_Ambiente.setWindowTitle(_translate("Liberacao_Meio_Ambiente", "MainWindow"))
        self.Label_Seguranca.setText(_translate("Liberacao_Meio_Ambiente", "MEIO AMBIENTE"))
        self.checkBox_1.setText(_translate("Liberacao_Meio_Ambiente", "1- Isento de vazamentos de óleo;"))
        self.botao_continuar.setText(_translate("Liberacao_Meio_Ambiente", "CONTINUAR"))
        self.Label_titulo.setText(_translate("Liberacao_Meio_Ambiente", "Requisitos de Meio Ambiente de acordo com o equipamento:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Liberacao_Meio_Ambiente = QtWidgets.QMainWindow()
    ui = Ui_Liberacao_Meio_Ambiente()
    ui.setupUi(Liberacao_Meio_Ambiente)
    Liberacao_Meio_Ambiente.show()
    sys.exit(app.exec_())
