# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Liberação_Segurança.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Liberacao_Seguranca(object):
    def setupUi(self, Liberacao_Seguranca):
        Liberacao_Seguranca.setObjectName("Liberacao_Seguranca")
        Liberacao_Seguranca.resize(1290, 841)
        Liberacao_Seguranca.setMinimumSize(QtCore.QSize(1290, 841))
        Liberacao_Seguranca.setMaximumSize(QtCore.QSize(1290, 841))
        Liberacao_Seguranca.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(Liberacao_Seguranca)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_Borda = QtWidgets.QLabel(self.centralwidget)
        self.Label_Borda.setGeometry(QtCore.QRect(0, 783, 1290, 18))
        self.Label_Borda.setText("")
        self.Label_Borda.setPixmap(QtGui.QPixmap("Imagens/Borda.png"))
        self.Label_Borda.setScaledContents(True)
        self.Label_Borda.setObjectName("Label_Borda")
        self.Liberacao_Seguranca_2 = QtWidgets.QFrame(self.centralwidget)
        self.Liberacao_Seguranca_2.setGeometry(QtCore.QRect(10, 10, 1270, 760))
        self.Liberacao_Seguranca_2.setStyleSheet("background-color: rgb(155, 228, 179);\n"
"border-style: outset;\n"
"\n"
"\n"
"\n"
"\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:6px;\n"
"")
        self.Liberacao_Seguranca_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Liberacao_Seguranca_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Liberacao_Seguranca_2.setObjectName("Liberacao_Seguranca_2")
        self.Label_Seguranca = QtWidgets.QLabel(self.Liberacao_Seguranca_2)
        self.Label_Seguranca.setGeometry(QtCore.QRect(340, 10, 601, 121))
        self.Label_Seguranca.setStyleSheet("border-style: outset;\n"
"\n"
"\n"
"\n"
"\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:0px;\n"
"\n"
"font: 75 65pt \"Bosch Sans Bold\";")
        self.Label_Seguranca.setObjectName("Label_Seguranca")
        self.checkBox_1 = QtWidgets.QCheckBox(self.Liberacao_Seguranca_2)
        self.checkBox_1.setGeometry(QtCore.QRect(60, 210, 350, 91))
        self.checkBox_1.setStyleSheet("\n"
"\n"
"\n"
"QCheckBox::indicator\n"
"{\n"
"width : 37px;\n"
"height : 37px;\n"
"background-color:white;\n"
"border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:3px;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"   background-color:rgb(255, 207, 0);\n"
"}\n"
"\n"
"border-style: inside;\n"
"\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:0px;\n"
"font: 75 25pt \"Bosch Sans Bold\";")
        self.checkBox_1.setObjectName("checkBox_1")
        self.botao_continuar = QtWidgets.QPushButton(self.Liberacao_Seguranca_2)
        self.botao_continuar.setGeometry(QtCore.QRect(890, 580, 321, 141))
        self.botao_continuar.setStyleSheet("background-color: rgb(255, 207, 0);\n"
"border-style: outset;\n"
"border-radius: 35px;\n"
"\n"
"\n"
"\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:4px;\n"
"\n"
"font: 75 35pt \"Bosch Sans Bold\";")
        self.botao_continuar.setObjectName("botao_continuar")
        self.checkBox_2 = QtWidgets.QCheckBox(self.Liberacao_Seguranca_2)
        self.checkBox_2.setGeometry(QtCore.QRect(60, 310, 441, 91))
        self.checkBox_2.setStyleSheet("\n"
"\n"
"\n"
"QCheckBox::indicator\n"
"{\n"
"width : 37px;\n"
"height : 37px;\n"
"background-color:white;\n"
"border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:3px;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"   background-color:rgb(255, 207, 0);\n"
"}\n"
"\n"
"border-style: inside;\n"
"\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:0px;\n"
"font: 75 25pt \"Bosch Sans Bold\";\n"
"")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.Liberacao_Seguranca_2)
        self.checkBox_3.setGeometry(QtCore.QRect(60, 420, 381, 71))
        self.checkBox_3.setStyleSheet("\n"
"\n"
"\n"
"QCheckBox::indicator\n"
"{\n"
"width : 37px;\n"
"height : 37px;\n"
"background-color:white;\n"
"border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:3px;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"   background-color:rgb(255, 207, 0);\n"
"}\n"
"\n"
"border-style: inside;\n"
"\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:0px;\n"
"font: 75 25pt \"Bosch Sans Bold\";")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.Liberacao_Seguranca_2)
        self.checkBox_4.setGeometry(QtCore.QRect(60, 530, 381, 61))
        self.checkBox_4.setStyleSheet("\n"
"\n"
"\n"
"QCheckBox::indicator\n"
"{\n"
"width : 37px;\n"
"height : 37px;\n"
"background-color:white;\n"
"border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:3px;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"   background-color:rgb(255, 207, 0);\n"
"}\n"
"\n"
"border-style: inside;\n"
"\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:0px;\n"
"font: 75 25pt \"Bosch Sans Bold\";")
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.Liberacao_Seguranca_2)
        self.checkBox_5.setGeometry(QtCore.QRect(60, 630, 461, 71))
        self.checkBox_5.setStyleSheet("\n"
"\n"
"\n"
"QCheckBox::indicator\n"
"{\n"
"width : 37px;\n"
"height : 37px;\n"
"background-color:white;\n"
"border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:3px;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"   background-color:rgb(255, 207, 0);\n"
"}\n"
"\n"
"border-style: inside;\n"
"\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:0px;\n"
"font: 75 25pt \"Bosch Sans Bold\";")
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.Liberacao_Seguranca_2)
        self.checkBox_6.setGeometry(QtCore.QRect(730, 200, 441, 91))
        self.checkBox_6.setStyleSheet("\n"
"\n"
"\n"
"QCheckBox::indicator\n"
"{\n"
"width : 37px;\n"
"height : 37px;\n"
"background-color:white;\n"
"border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:3px;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"   background-color:rgb(255, 207, 0);\n"
"}\n"
"\n"
"border-style: inside;\n"
"\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:0px;\n"
"font: 75 25pt \"Bosch Sans Bold\";")
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.Liberacao_Seguranca_2)
        self.checkBox_7.setGeometry(QtCore.QRect(730, 290, 381, 91))
        self.checkBox_7.setStyleSheet("\n"
"\n"
"\n"
"QCheckBox::indicator\n"
"{\n"
"width : 37px;\n"
"height : 37px;\n"
"background-color:white;\n"
"border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:3px;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"   background-color:rgb(255, 207, 0);\n"
"}\n"
"\n"
"border-style: inside;\n"
"\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:0px;\n"
"font: 75 25pt \"Bosch Sans Bold\";")
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.Liberacao_Seguranca_2)
        self.checkBox_8.setGeometry(QtCore.QRect(730, 380, 501, 91))
        self.checkBox_8.setStyleSheet("\n"
"\n"
"\n"
"QCheckBox::indicator\n"
"{\n"
"width : 37px;\n"
"height : 37px;\n"
"background-color:white;\n"
"border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:3px;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"   background-color:rgb(255, 207, 0);\n"
"}\n"
"\n"
"border-style: inside;\n"
"\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:0px;\n"
"font: 75 25pt \"Bosch Sans Bold\";\n"
"")
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.Liberacao_Seguranca_2)
        self.checkBox_9.setGeometry(QtCore.QRect(730, 470, 491, 91))
        self.checkBox_9.setStyleSheet("\n"
"\n"
"\n"
"QCheckBox::indicator\n"
"{\n"
"width : 37px;\n"
"height : 37px;\n"
"background-color:white;\n"
"border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:3px;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"   background-color:rgb(255, 207, 0);\n"
"}\n"
"\n"
"border-style: inside;\n"
"\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:0px;\n"
"font: 75 25pt \"Bosch Sans Bold\";")
        self.checkBox_9.setObjectName("checkBox_9")
        self.Label_titulo = QtWidgets.QLabel(self.Liberacao_Seguranca_2)
        self.Label_titulo.setGeometry(QtCore.QRect(60, 140, 941, 51))
        self.Label_titulo.setStyleSheet("border-style: outset;\n"
"\n"
"\n"
"\n"
"\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:0px;\n"
"\n"
"font: 75 25pt \"Bosch Sans Bold\";")
        self.Label_titulo.setObjectName("Label_titulo")
        self.botao_home = QtWidgets.QPushButton(self.Liberacao_Seguranca_2)
        self.botao_home.setGeometry(QtCore.QRect(1150, 0, 120, 120))
        self.botao_home.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;")
        self.botao_home.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imagens/Home.Liberacao.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_home.setIcon(icon)
        self.botao_home.setIconSize(QtCore.QSize(105, 105))
        self.botao_home.setObjectName("botao_home")
        Liberacao_Seguranca.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Liberacao_Seguranca)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1290, 21))
        self.menubar.setObjectName("menubar")
        Liberacao_Seguranca.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Liberacao_Seguranca)
        self.statusbar.setObjectName("statusbar")
        Liberacao_Seguranca.setStatusBar(self.statusbar)

        self.retranslateUi(Liberacao_Seguranca)
        QtCore.QMetaObject.connectSlotsByName(Liberacao_Seguranca)

    def retranslateUi(self, Liberacao_Seguranca):
        _translate = QtCore.QCoreApplication.translate
        Liberacao_Seguranca.setWindowTitle(_translate("Liberacao_Seguranca", "Liberacao_Seguranca"))
        self.Label_Seguranca.setText(_translate("Liberacao_Seguranca", "SEGURANÇA"))
        self.checkBox_1.setText(_translate("Liberacao_Seguranca", "1- Proteções;"))
        self.botao_continuar.setText(_translate("Liberacao_Seguranca", "CONTINUAR"))
        self.checkBox_2.setText(_translate("Liberacao_Seguranca", "2- Parafusos de Fixação;"))
        self.checkBox_3.setText(_translate("Liberacao_Seguranca", "3- Fiação;"))
        self.checkBox_4.setText(_translate("Liberacao_Seguranca", "4- Mangueiras;"))
        self.checkBox_5.setText(_translate("Liberacao_Seguranca", "5- Botão de Emergência;"))
        self.checkBox_6.setText(_translate("Liberacao_Seguranca", "6- Botões de Comando;"))
        self.checkBox_7.setText(_translate("Liberacao_Seguranca", "7- Chave Geral;"))
        self.checkBox_8.setText(_translate("Liberacao_Seguranca", "8- Painel Elétrico Fechado;"))
        self.checkBox_9.setText(_translate("Liberacao_Seguranca", "9- Fixação de Ferramental;"))
        self.Label_titulo.setText(_translate("Liberacao_Seguranca", "Requisitos de Segurança de acordo com o equipamento:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Liberacao_Seguranca = QtWidgets.QMainWindow()
    ui = Ui_Liberacao_Seguranca()
    ui.setupUi(Liberacao_Seguranca)
    Liberacao_Seguranca.show()
    sys.exit(app.exec_())
