# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menu02.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Menu02(object):
    def setupUi(self, Menu02):
        Menu02.setObjectName("Menu02")
        Menu02.resize(1290, 841)
        Menu02.setMinimumSize(QtCore.QSize(1275, 841))
        Menu02.setMaximumSize(QtCore.QSize(1290, 841))
        Menu02.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(Menu02)
        self.centralwidget.setObjectName("centralwidget")
        self.Botao_PH = QtWidgets.QPushButton(self.centralwidget)
        self.Botao_PH.setGeometry(QtCore.QRect(672, 240, 240, 240))
        self.Botao_PH.setStyleSheet("border-style: outset;\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;")
        self.Botao_PH.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imagens/PH.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Botao_PH.setIcon(icon)
        self.Botao_PH.setIconSize(QtCore.QSize(220, 220))
        self.Botao_PH.setObjectName("Botao_PH")
        self.Botao_Manutencao = QtWidgets.QPushButton(self.centralwidget)
        self.Botao_Manutencao.setGeometry(QtCore.QRect(63, 240, 240, 240))
        self.Botao_Manutencao.setStyleSheet("border-style: outset;\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;")
        self.Botao_Manutencao.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("imagens/MANUTENCAO.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Botao_Manutencao.setIcon(icon1)
        self.Botao_Manutencao.setIconSize(QtCore.QSize(220, 220))
        self.Botao_Manutencao.setObjectName("Botao_Manutencao")
        self.Botao_Cadastros = QtWidgets.QPushButton(self.centralwidget)
        self.Botao_Cadastros.setGeometry(QtCore.QRect(365, 240, 240, 240))
        self.Botao_Cadastros.setStyleSheet("border-style: outset;\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;")
        self.Botao_Cadastros.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("imagens/CADASTROS.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Botao_Cadastros.setIcon(icon2)
        self.Botao_Cadastros.setIconSize(QtCore.QSize(220, 220))
        self.Botao_Cadastros.setObjectName("Botao_Cadastros")
        self.Botao_Sair = QtWidgets.QPushButton(self.centralwidget)
        self.Botao_Sair.setGeometry(QtCore.QRect(980, 240, 240, 240))
        self.Botao_Sair.setStyleSheet("border-style: outset;\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;")
        self.Botao_Sair.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("imagens/SAIR.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Botao_Sair.setIcon(icon3)
        self.Botao_Sair.setIconSize(QtCore.QSize(220, 220))
        self.Botao_Sair.setObjectName("Botao_Sair")
        self.Label_Borda = QtWidgets.QLabel(self.centralwidget)
        self.Label_Borda.setGeometry(QtCore.QRect(0, 783, 1290, 18))
        self.Label_Borda.setText("")
        self.Label_Borda.setPixmap(QtGui.QPixmap("Imagens/Borda.png"))
        self.Label_Borda.setScaledContents(True)
        self.Label_Borda.setObjectName("Label_Borda")
        self.Botao_Seta_Direita = QtWidgets.QPushButton(self.centralwidget)
        self.Botao_Seta_Direita.setGeometry(QtCore.QRect(1153, 601, 111, 141))
        self.Botao_Seta_Direita.setStyleSheet("border-style: inside;\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:3px;")
        self.Botao_Seta_Direita.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("imagens/Seta Branca para direita.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Botao_Seta_Direita.setIcon(icon4)
        self.Botao_Seta_Direita.setIconSize(QtCore.QSize(135, 135))
        self.Botao_Seta_Direita.setObjectName("Botao_Seta_Direita")
        self.Botao_Seta_Esquerda = QtWidgets.QPushButton(self.centralwidget)
        self.Botao_Seta_Esquerda.setGeometry(QtCore.QRect(1000, 590, 121, 161))
        self.Botao_Seta_Esquerda.setStyleSheet("border-style: inside;\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:3px;")
        self.Botao_Seta_Esquerda.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("imagens/Seta Preta para esquerda.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Botao_Seta_Esquerda.setIcon(icon5)
        self.Botao_Seta_Esquerda.setIconSize(QtCore.QSize(137, 137))
        self.Botao_Seta_Esquerda.setObjectName("Botao_Seta_Esquerda")
        self.Label_Menu_De_Usuario = QtWidgets.QLabel(self.centralwidget)
        self.Label_Menu_De_Usuario.setGeometry(QtCore.QRect(210, 40, 875, 121))
        self.Label_Menu_De_Usuario.setStyleSheet("border-style: outset;\n"
"\n"
"\n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:0px;\n"
"\n"
"font: 75 65pt \"Bosch Sans Bold\";")
        self.Label_Menu_De_Usuario.setObjectName("Label_Menu_De_Usuario")
        self.Label_Colaborador = QtWidgets.QLabel(self.centralwidget)
        self.Label_Colaborador.setGeometry(QtCore.QRect(60, 650, 551, 41))
        self.Label_Colaborador.setStyleSheet("border-style: outset;\n"
"\n"
"\n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:0px;\n"
"\n"
"font: 75 20pt \"Bosch Sans Bold\";")
        self.Label_Colaborador.setObjectName("Label_Colaborador")
        self.Label_EDV = QtWidgets.QLabel(self.centralwidget)
        self.Label_EDV.setGeometry(QtCore.QRect(60, 700, 371, 41))
        self.Label_EDV.setStyleSheet("border-style: outset;\n"
"\n"
"\n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:0px;\n"
"\n"
"font: 75 20pt \"Bosch Sans Bold\";")
        self.Label_EDV.setObjectName("Label_EDV")
        Menu02.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Menu02)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1290, 21))
        self.menubar.setObjectName("menubar")
        Menu02.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Menu02)
        self.statusbar.setObjectName("statusbar")
        Menu02.setStatusBar(self.statusbar)

        self.retranslateUi(Menu02)
        QtCore.QMetaObject.connectSlotsByName(Menu02)

    def retranslateUi(self, Menu02):
        _translate = QtCore.QCoreApplication.translate
        Menu02.setWindowTitle(_translate("Menu02", "Menu02"))
        self.Botao_Manutencao.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.Label_Menu_De_Usuario.setText(_translate("MainWindow", "MENU DE USUÁRIO"))
        self.Label_Colaborador.setText(_translate("MainWindow", "COLABORADOR:"))
        self.Label_EDV.setText(_translate("MainWindow", "EDV:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Menu02 = QtWidgets.QMainWindow()
    ui = Ui_Menu02()
    ui.setupUi(Menu02)
    Menu02.show()
    sys.exit(app.exec_())
