# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Registros_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Registros_menu(object):
    def setupUi(self, Registros_menu):
        Registros_menu.setObjectName("Registros_menu")
        Registros_menu.resize(1290, 841)
        Registros_menu.setMinimumSize(QtCore.QSize(1290, 841))
        Registros_menu.setMaximumSize(QtCore.QSize(1290, 841))
        Registros_menu.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(Registros_menu)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_Borda = QtWidgets.QLabel(self.centralwidget)
        self.Label_Borda.setGeometry(QtCore.QRect(0, 783, 1290, 18))
        self.Label_Borda.setText("")
        self.Label_Borda.setPixmap(QtGui.QPixmap("Imagens/Borda.png"))
        self.Label_Borda.setScaledContents(True)
        self.Label_Borda.setObjectName("Label_Borda")
        self.botao_historico_utilizacao_02 = QtWidgets.QPushButton(self.centralwidget)
        self.botao_historico_utilizacao_02.setGeometry(QtCore.QRect(170, 120, 911, 161))
        self.botao_historico_utilizacao_02.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(234, 229, 239);\n"
"border-width:7px;\n"
"font: 75 40pt \"Bosch Sans Bold\";\n"
"border-radius: 30px;")
        self.botao_historico_utilizacao_02.setObjectName("botao_historico_utilizacao_02")
        self.botao_historico_utilizacao_01 = QtWidgets.QPushButton(self.centralwidget)
        self.botao_historico_utilizacao_01.setGeometry(QtCore.QRect(40, 100, 200, 200))
        self.botao_historico_utilizacao_01.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(155, 228, 179);\n"
"border-width:7px;\n"
"border-radius: 100px;\n"
"font: 75 50pt \"Bosch Sans Bold\";")
        self.botao_historico_utilizacao_01.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imagens/Historico_Utilizacao.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_historico_utilizacao_01.setIcon(icon)
        self.botao_historico_utilizacao_01.setIconSize(QtCore.QSize(110, 110))
        self.botao_historico_utilizacao_01.setObjectName("botao_historico_utilizacao_01")
        self.botao_relatorio_defeitos_02 = QtWidgets.QPushButton(self.centralwidget)
        self.botao_relatorio_defeitos_02.setGeometry(QtCore.QRect(170, 420, 911, 161))
        self.botao_relatorio_defeitos_02.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(234, 229, 239);\n"
"border-width:7px;\n"
"font: 75 40pt \"Bosch Sans Bold\";\n"
"border-radius: 30px;")
        self.botao_relatorio_defeitos_02.setObjectName("botao_relatorio_defeitos_02")
        self.botao_relatorio_defeitos_01 = QtWidgets.QPushButton(self.centralwidget)
        self.botao_relatorio_defeitos_01.setGeometry(QtCore.QRect(40, 400, 200, 200))
        self.botao_relatorio_defeitos_01.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 207, 0);\n"
"border-width:7px;\n"
"border-radius: 100px;\n"
"font: 75 50pt \"Bosch Sans Bold\";")
        self.botao_relatorio_defeitos_01.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("imagens/Relatorio_defeitos.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_relatorio_defeitos_01.setIcon(icon1)
        self.botao_relatorio_defeitos_01.setIconSize(QtCore.QSize(160, 160))
        self.botao_relatorio_defeitos_01.setObjectName("botao_relatorio_defeitos_01")
        self.botao_home = QtWidgets.QPushButton(self.centralwidget)
        self.botao_home.setGeometry(QtCore.QRect(1150, 10, 120, 120))
        self.botao_home.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;")
        self.botao_home.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("imagens/Home_Registros.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_home.setIcon(icon2)
        self.botao_home.setIconSize(QtCore.QSize(105, 105))
        self.botao_home.setObjectName("botao_home")
        Registros_menu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Registros_menu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1290, 21))
        self.menubar.setObjectName("menubar")
        Registros_menu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Registros_menu)
        self.statusbar.setObjectName("statusbar")
        Registros_menu.setStatusBar(self.statusbar)

        self.retranslateUi(Registros_menu)
        QtCore.QMetaObject.connectSlotsByName(Registros_menu)

    def retranslateUi(self, Registros_menu):
        _translate = QtCore.QCoreApplication.translate
        Registros_menu.setWindowTitle(_translate("Registros_menu", "MainWindow"))
        self.botao_historico_utilizacao_02.setText(_translate("Registros_menu", "  HISTÓRICO DE UTILIZAÇÃO"))
        self.botao_relatorio_defeitos_02.setText(_translate("Registros_menu", "RELATÓRIOS DE DEFEITOS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Registros_menu = QtWidgets.QMainWindow()
    ui = Ui_Registros_menu()
    ui.setupUi(Registros_menu)
    Registros_menu.show()
    sys.exit(app.exec_())
