# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Usuario_registrado.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Usuario_registrado(object):
    def setupUi(self, Usuario_registrado):
        Usuario_registrado.setObjectName("Usuario_registrado")
        Usuario_registrado.resize(1290, 841)
        Usuario_registrado.setMinimumSize(QtCore.QSize(1290, 841))
        Usuario_registrado.setMaximumSize(QtCore.QSize(1290, 841))
        Usuario_registrado.setStyleSheet("background-color: rgb(255, 255, 255);")
        Usuario_registrado.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(Usuario_registrado)
        self.centralwidget.setObjectName("centralwidget")
        self.label_fundo = QtWidgets.QLabel(self.centralwidget)
        self.label_fundo.setGeometry(QtCore.QRect(20, 10, 1251, 731))
        self.label_fundo.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:5px;\n"
"font: 75 85pt \"Bosch Sans Bold\";\n"
"border-radius: 90px;\n"
"background-color: rgb(155, 228, 179);")
        self.label_fundo.setText("")
        self.label_fundo.setObjectName("label_fundo")
        self.label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo.setGeometry(QtCore.QRect(150, 60, 1021, 111))
        self.label_titulo.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:0px;\n"
"font: 75 60pt \"Bosch Sans Bold\";\n"
"border-radius: 75px;\n"
"background-color: rgb(155, 228, 179);")
        self.label_titulo.setObjectName("label_titulo")
        self.label_check = QtWidgets.QLabel(self.centralwidget)
        self.label_check.setGeometry(QtCore.QRect(460, 320, 361, 251))
        self.label_check.setStyleSheet("border-style: outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:0px;\n"
"font: 75 60pt \"Bosch Sans Bold\";\n"
"border-radius: 75px;\n"
"background-color: rgb(155, 228, 179);")
        self.label_check.setText("")
        self.label_check.setPixmap(QtGui.QPixmap("imagens/check.png"))
        self.label_check.setScaledContents(True)
        self.label_check.setObjectName("label_check")
        self.label_Borda = QtWidgets.QLabel(self.centralwidget)
        self.label_Borda.setGeometry(QtCore.QRect(0, 783, 1290, 18))
        self.label_Borda.setText("")
        self.label_Borda.setPixmap(QtGui.QPixmap("imagens/Borda.png"))
        self.label_Borda.setScaledContents(True)
        self.label_Borda.setObjectName("label_Borda")
        Usuario_registrado.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Usuario_registrado)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1290, 21))
        self.menubar.setObjectName("menubar")
        Usuario_registrado.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Usuario_registrado)
        self.statusbar.setObjectName("statusbar")
        Usuario_registrado.setStatusBar(self.statusbar)

        self.retranslateUi(Usuario_registrado)
        QtCore.QMetaObject.connectSlotsByName(Usuario_registrado)

    def retranslateUi(self, Usuario_registrado):
        _translate = QtCore.QCoreApplication.translate
        Usuario_registrado.setWindowTitle(_translate("Usuario_registrado", "MainWindow"))
        self.label_titulo.setText(_translate("Usuario_registrado", "USUÁRIO REGISTRADO!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Usuario_registrado = QtWidgets.QMainWindow()
    ui = Ui_Usuario_registrado()
    ui.setupUi(Usuario_registrado)
    Usuario_registrado.show()
    sys.exit(app.exec_())
