# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'verificaPC.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

import socket
import mysql.connector
from datetime import datetime
import os

class Ui_MainWindow(object):
    def __init__(self):
        self.name=''
        self.con = mysql.connector.connect(host='localhost',database='checkpc',user='root')

        self.hora = '0000-00-00 00:00:00'
        self.horaBD = '0000-00-00 00:00:00'
        self.ctrl1 =False
        self.ctrl2 = False
        self.ctrl3 = False
        self.ctrl4 = False
        self.ctrl5 = False
        self.ctrl6 = False
        self.ctrl7 = False
        self.ctrl8 = False
        self.edv = ''
        self.edvInt = 0
        self.cursor = self.con.cursor()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(888, 621)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 931, 581))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/Fita.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(120, 190, 641, 381))
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 622, 590))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.widget.setEnabled(False)
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox6 = QtWidgets.QGroupBox(self.widget)
        self.groupBox6.setStyleSheet("border:none;")
        self.groupBox6.setTitle("")
        self.groupBox6.setObjectName("groupBox6")
        self.radioButton62 = QtWidgets.QRadioButton(self.groupBox6)
        self.radioButton62.setGeometry(QtCore.QRect(50, 0, 43, 16))
        font = QtGui.QFont()
        font.setFamily("Bosch Office Sans")
        font.setBold(False)
        font.setWeight(50)
        self.radioButton62.setFont(font)
        self.radioButton62.setObjectName("radioButton62")
        self.radioButton61 = QtWidgets.QRadioButton(self.groupBox6)
        self.radioButton61.setGeometry(QtCore.QRect(0, 0, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Bosch Office Sans")
        font.setBold(False)
        font.setWeight(50)
        self.radioButton61.setFont(font)
        self.radioButton61.setObjectName("radioButton61")
        self.gridLayout.addWidget(self.groupBox6, 11, 2, 1, 2)
        self.groupBox7 = QtWidgets.QGroupBox(self.widget)
        self.groupBox7.setStyleSheet("border:none;")
        self.groupBox7.setTitle("")
        self.groupBox7.setObjectName("groupBox7")
        self.radioButton72 = QtWidgets.QRadioButton(self.groupBox7)
        self.radioButton72.setGeometry(QtCore.QRect(50, 0, 43, 16))
        font = QtGui.QFont()
        font.setFamily("Bosch Office Sans")
        font.setBold(False)
        font.setWeight(50)
        self.radioButton72.setFont(font)
        self.radioButton72.setObjectName("radioButton72")
        self.radioButton71 = QtWidgets.QRadioButton(self.groupBox7)
        self.radioButton71.setGeometry(QtCore.QRect(0, 0, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Bosch Office Sans")
        font.setBold(False)
        font.setWeight(50)
        self.radioButton71.setFont(font)
        self.radioButton71.setObjectName("radioButton71")
        self.gridLayout.addWidget(self.groupBox7, 12, 2, 1, 2)
        self.comboBox_2 = QtWidgets.QComboBox(self.widget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.setEnabled(False)
        self.gridLayout.addWidget(self.comboBox_2, 4, 4, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Bosch Office Sans")
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 12, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Bosch Office Sans")
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setWordWrap(True)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 10, 1, 1, 1)
        self.txtPastaDel = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtPastaDel.sizePolicy().hasHeightForWidth())
        self.txtPastaDel.setSizePolicy(sizePolicy)
        self.txtPastaDel.setObjectName("txtPastaDel")
        self.gridLayout.addWidget(self.txtPastaDel, 13, 4, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 14, 4, 1, 1)
        self.groupBox2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox2.setStyleSheet("border:none;")
        self.groupBox2.setTitle("")
        self.groupBox2.setObjectName("groupBox2")
        self.radioButton22 = QtWidgets.QRadioButton(self.groupBox2)
        self.radioButton22.setGeometry(QtCore.QRect(50, 0, 43, 16))
        font = QtGui.QFont()
        font.setFamily("Bosch Office Sans")
        font.setBold(False)
        font.setWeight(50)
        self.radioButton22.setFont(font)
        self.radioButton22.setObjectName("radioButton22")
        self.radioButton21 = QtWidgets.QRadioButton(self.groupBox2)
        self.radioButton21.setGeometry(QtCore.QRect(0, 0, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Bosch Office Sans")
        font.setBold(False)
        font.setWeight(50)
        self.radioButton21.setFont(font)
        self.radioButton21.setObjectName("radioButton21")
        self.gridLayout.addWidget(self.groupBox2, 4, 2, 1, 2)
        self.groupBox5 = QtWidgets.QGroupBox(self.widget)
        self.groupBox5.setStyleSheet("border:none;")
        self.groupBox5.setTitle("")
        self.groupBox5.setObjectName("groupBox5")
        self.radioButton52 = QtWidgets.QRadioButton(self.groupBox5)
        self.radioButton52.setGeometry(QtCore.QRect(50, 0, 43, 16))
        font = QtGui.QFont()
        font.setFamily("Bosch Office Sans")
        font.setBold(False)
        font.setWeight(50)
        self.radioButton52.setFont(font)
        self.radioButton52.setObjectName("radioButton52")
        self.radioButton51 = QtWidgets.QRadioButton(self.groupBox5)
        self.radioButton51.setGeometry(QtCore.QRect(0, 0, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Bosch Office Sans")
        font.setBold(False)
        font.setWeight(50)
        self.radioButton51.setFont(font)
        self.radioButton51.setObjectName("radioButton51")
        self.gridLayout.addWidget(self.groupBox5, 10, 2, 1, 2)
        self.groupBox4 = QtWidgets.QGroupBox(self.widget)
        self.groupBox4.setStyleSheet("border:none;")
        self.groupBox4.setTitle("")
        self.groupBox4.setObjectName("groupBox4")
        self.radioButton42 = QtWidgets.QRadioButton(self.groupBox4)
        self.radioButton42.setGeometry(QtCore.QRect(50, 0, 43, 16))
        font = QtGui.QFont()
        font.setFamily("Bosch Office Sans")
        font.setBold(False)
        font.setWeight(50)
        self.radioButton42.setFont(font)
        self.radioButton42.setObjectName("radioButton42")
        self.radioButton41 = QtWidgets.QRadioButton(self.groupBox4)
        self.radioButton41.setGeometry(QtCore.QRect(0, 0, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Bosch Office Sans")
        font.setBold(False)
        font.setWeight(50)
        self.radioButton41.setFont(font)
        self.radioButton41.setObjectName("radioButton41")
        self.gridLayout.addWidget(self.groupBox4, 8, 2, 1, 2)
        self.label_26 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Bosch Office Sans")
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 8, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Bosch Office Sans")
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setWordWrap(True)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 6, 1, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.widget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.setEnabled(False)
        self.gridLayout.addWidget(self.comboBox_3, 6, 4, 1, 1)
        self.txtAttSoftwareAutorizacao = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAttSoftwareAutorizacao.sizePolicy().hasHeightForWidth())
        self.txtAttSoftwareAutorizacao.setSizePolicy(sizePolicy)
        self.txtAttSoftwareAutorizacao.setObjectName("txtAttSoftwareAutorizacao")
        self.gridLayout.addWidget(self.txtAttSoftwareAutorizacao, 11, 4, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Bosch Office Sans")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 7, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Bosch Office Sans")
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setWordWrap(True)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 13, 1, 1, 1)
        self.textEditObs = QtWidgets.QTextEdit(self.widget)
        self.textEditObs.setObjectName("textEditObs")
        self.gridLayout.addWidget(self.textEditObs, 15, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Bosch Office Sans")
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setWordWrap(True)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 11, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 1, 5, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bosch Office Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 5)
        self.label_17 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bosch Office Sans")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 1, 1, 1, 2)
        self.groupBox3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox3.setStyleSheet("border:none;")
        self.groupBox3.setTitle("")
        self.groupBox3.setObjectName("groupBox3")
        self.radioButton32 = QtWidgets.QRadioButton(self.groupBox3)
        self.radioButton32.setGeometry(QtCore.QRect(50, 0, 43, 16))
        font = QtGui.QFont()
        font.setFamily("Bosch Office Sans")
        font.setBold(False)
        font.setWeight(50)
        self.radioButton32.setFont(font)
        self.radioButton32.setObjectName("radioButton32")
        self.radioButton31 = QtWidgets.QRadioButton(self.groupBox3)
        self.radioButton31.setGeometry(QtCore.QRect(0, 0, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Bosch Office Sans")
        font.setBold(False)
        font.setWeight(50)
        self.radioButton31.setFont(font)
        self.radioButton31.setObjectName("radioButton31")
        self.gridLayout.addWidget(self.groupBox3, 6, 2, 1, 2)
        self.label_28 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Bosch Office Sans")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 14, 1, 1, 1)
        self.groupBox1 = QtWidgets.QGroupBox(self.widget)
        self.groupBox1.setStyleSheet("border:none;")
        self.groupBox1.setTitle("")
        self.groupBox1.setObjectName("groupBox1")
        self.radioButton11 = QtWidgets.QRadioButton(self.groupBox1)
        self.radioButton11.setGeometry(QtCore.QRect(50, 0, 43, 16))
        font = QtGui.QFont()
        font.setFamily("Bosch Office Sans")
        font.setBold(False)
        font.setWeight(50)
        self.radioButton11.setFont(font)
        self.radioButton11.setObjectName("radioButton11")
        self.radioButton11.clicked.connect(self.BlockCB)
        self.radioButton12 = QtWidgets.QRadioButton(self.groupBox1)
        self.radioButton12.setGeometry(QtCore.QRect(0, 0, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Bosch Office Sans")
        font.setBold(False)
        font.setWeight(50)
        self.radioButton12.setFont(font)
        self.radioButton12.setObjectName("radioButton12")

        self.gridLayout.addWidget(self.groupBox1, 3, 2, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 1, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Bosch Office Sans")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 1, 1, 1)

        self.txtAttSoftware = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAttSoftware.sizePolicy().hasHeightForWidth())
        self.txtAttSoftware.setSizePolicy(sizePolicy)
        self.txtAttSoftware.setObjectName("txtAttSoftware")
        self.gridLayout.addWidget(self.txtAttSoftware, 10, 4, 1, 1)


        self.label_8 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Bosch Office Sans")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setEnabled(False)
        self.gridLayout.addWidget(self.comboBox, 3, 4, 1, 1)
        self.btnEnviar = QtWidgets.QPushButton(self.widget)
        self.btnEnviar.setStyleSheet("background-color: rgb(24, 131, 126);\n"
"color: rgb(255, 255, 255);")
        self.btnEnviar.setObjectName("btnEnviar")

        self.btnEnviar.clicked.connect(self.tudoVerificado)


        self.gridLayout.addWidget(self.btnEnviar, 16, 4, 1, 1)
        self.txtEspDisk = QtWidgets.QLineEdit(self.widget)
        self.txtEspDisk.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtEspDisk.sizePolicy().hasHeightForWidth())
        self.txtEspDisk.setSizePolicy(sizePolicy)
        self.txtEspDisk.setObjectName("txtEspDisk")
        self.gridLayout.addWidget(self.txtEspDisk, 12, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 14, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 14, 3, 1, 1)
        self.groupBox7_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox7_2.setStyleSheet("border:none;")
        self.groupBox7_2.setTitle("")
        self.groupBox7_2.setObjectName("groupBox7_2")
        self.radioButton72_2 = QtWidgets.QRadioButton(self.groupBox7_2)
        self.radioButton72_2.setGeometry(QtCore.QRect(50, 0, 43, 16))
        font = QtGui.QFont()
        font.setFamily("Bosch Office Sans")
        font.setBold(False)
        font.setWeight(50)
        self.radioButton72_2.setFont(font)
        self.radioButton72_2.setObjectName("radioButton72_2")
        self.radioButton71_2 = QtWidgets.QRadioButton(self.groupBox7_2)
        self.radioButton71_2.setGeometry(QtCore.QRect(0, 0, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Bosch Office Sans")
        font.setBold(False)
        font.setWeight(50)
        self.radioButton71_2.setFont(font)
        self.radioButton71_2.setObjectName("radioButton71_2")
        self.gridLayout.addWidget(self.groupBox7_2, 13, 2, 1, 2)
        self.verticalLayout.addWidget(self.widget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(120, 20, 641, 171))
        self.widget_2.setAutoFillBackground(False)
        self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_2.setObjectName("widget_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(140, 100, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_29 = QtWidgets.QLabel(self.widget_2)
        self.label_29.setGeometry(QtCore.QRect(0, 50, 641, 32))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setWordWrap(True)
        self.label_29.setObjectName("label_29")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(350, 100, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.txtEDV = QtWidgets.QLineEdit(self.widget_2)
        self.txtEDV.setGeometry(QtCore.QRect(140, 120, 151, 20))
        self.txtEDV.setObjectName("txtEDV")
        self.txtUser = QtWidgets.QLineEdit(self.widget_2)
        self.txtUser.setEnabled(False)
        self.txtUser.setGeometry(QtCore.QRect(350, 120, 151, 20))
        self.txtUser.setObjectName("txtUser")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(480, 0, 161, 61))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("img/Logo ets.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.btnOK = QtWidgets.QPushButton(self.widget_2)
        self.btnOK.setGeometry(QtCore.QRect(510, 120, 41, 23))
        self.btnOK.clicked.connect(self.verificaEDV)
        self.btnOK.setStyleSheet("background-color: rgb(24, 131, 126);\n"
"color: rgb(255, 255, 255);")
        self.btnOK.setObjectName("btnOK")
        self.label_30 = QtWidgets.QLabel(self.widget_2)
        self.label_30.setGeometry(QtCore.QRect(10, 10, 161, 32))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setText("")
        self.label_30.setPixmap(QtGui.QPixmap("img/BOSCH_RGB.png"))
        self.label_30.setScaledContents(True)
        self.label_30.setWordWrap(True)
        self.label_30.setObjectName("label_30")
        self.label_10 = QtWidgets.QLabel(self.widget_2)
        self.label_10.setGeometry(QtCore.QRect(310, 110, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("img/desktop.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_14 = QtWidgets.QLabel(self.widget_2)
        self.label_14.setGeometry(QtCore.QRect(100, 110, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("S:/PM/ter/ets/Inter_Setor/COMPARTILHADO/APRENDIZES/Smart Automation - 2ª Turma/Danyelly Silveira Cirilo/Python/ProjetoLiberacaoPC/img/my-brand-frame.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 888, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.label_29.setText('BOM DIA')
        self.nomeHoste()
        self.horaSistema()
        self.conxaoDB()
        self.txtEDV.setFocus()

        self.txtAttSoftwareAutorizacao.setEnabled(False)
        self.txtAttSoftware.setEnabled(False)
        self.txtPastaDel.setEnabled(False)

        self.radioButton12.clicked.connect(lambda: self.LiberaCB(str(self.radioButton12.objectName())))
        self.radioButton21.clicked.connect(lambda: self.LiberaCB(str(self.radioButton21.objectName())))
        self.radioButton31.clicked.connect(lambda: self.LiberaCB(str(self.radioButton31.objectName())))
        self.radioButton41.clicked.connect(lambda: self.LiberaCB(str(self.radioButton41.objectName())))
        self.radioButton51.clicked.connect(lambda: self.LiberaCB(str(self.radioButton51.objectName())))
        self.radioButton61.clicked.connect(lambda: self.LiberaCB(str(self.radioButton61.objectName())))
        self.radioButton71.clicked.connect(lambda: self.LiberaCB(str(self.radioButton71.objectName())))
        self.radioButton71_2.clicked.connect(lambda: self.LiberaCB(str(self.radioButton71_2.objectName())))

        self.radioButton11.clicked.connect(lambda: self.BlockCB(str(self.radioButton11.objectName())))
        self.radioButton22.clicked.connect(lambda: self.BlockCB(str(self.radioButton22.objectName())))
        self.radioButton32.clicked.connect(lambda: self.BlockCB(str(self.radioButton32.objectName())))
        self.radioButton42.clicked.connect(lambda: self.BlockCB(str(self.radioButton42.objectName())))
        self.radioButton52.clicked.connect(lambda: self.BlockCB(str(self.radioButton52.objectName())))
        self.radioButton62.clicked.connect(lambda: self.BlockCB(str(self.radioButton62.objectName())))
        self.radioButton72.clicked.connect(lambda: self.BlockCB(str(self.radioButton72.objectName())))
        self.radioButton72_2.clicked.connect(lambda: self.BlockCB(str(self.radioButton72_2.objectName())))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioButton62.setText(_translate("MainWindow", "Não"))
        self.radioButton61.setText(_translate("MainWindow", "Sim"))
        self.radioButton72.setText(_translate("MainWindow", "Não"))
        self.radioButton71.setText(_translate("MainWindow", "Sim"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", ""))
        self.comboBox_2.addItem("Mouse")
        self.comboBox_2.addItem("MousePad")
        self.comboBox_2.addItem("Teclado")
        self.comboBox_2.addItem("WebCam")
        self.comboBox_2.addItem("HeadFone")
        self.label_23.setText(_translate("MainWindow", "Espaço em disco é suficiente?"))
        self.label_27.setText(_translate("MainWindow", "Há alguma atualização de sofware?"))
        self.txtPastaDel.setText(_translate("MainWindow", ""))
        self.radioButton22.setText(_translate("MainWindow", "Não"))
        self.radioButton21.setText(_translate("MainWindow", "Sim"))
        self.radioButton52.setText(_translate("MainWindow", "Não"))
        self.radioButton51.setText(_translate("MainWindow", "Sim"))
        self.radioButton42.setText(_translate("MainWindow", "Não"))
        self.radioButton41.setText(_translate("MainWindow", "Sim"))
        self.label_26.setText(_translate("MainWindow", "Área de trabalho está limpa?"))
        self.label_19.setText(_translate("MainWindow", "Há algum periférico com problema?"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", ""))
        self.comboBox_3.addItem("Mouse")
        self.comboBox_3.addItem("MousePad")
        self.comboBox_3.addItem("Teclado")
        self.comboBox_3.addItem("WebCam")
        self.comboBox_3.addItem("HeadFone")
        self.txtAttSoftwareAutorizacao.setText(_translate("MainWindow", ""))
        self.label_25.setText(_translate("MainWindow", "Software"))
        self.label_24.setText(_translate("MainWindow", "Alguma pasta foi excluida ou movida para um lugar errado?"))
        self.label_21.setText(_translate("MainWindow", "Necessecita de autorização para instalar um software?"))
        self.label_7.setText(_translate("MainWindow", "CHECKLIST - Liberação do Desktop"))
        self.label_17.setText(_translate("MainWindow", "Posto de Trabalho                                         "))
        self.radioButton32.setText(_translate("MainWindow", "Não"))
        self.radioButton31.setText(_translate("MainWindow", "Sim"))
        self.label_28.setText(_translate("MainWindow", "Observações:"))
        self.radioButton11.setText(_translate("MainWindow", "Não"))
        self.radioButton12.setText(_translate("MainWindow", "Sim"))
        self.label_12.setText(_translate("MainWindow", "Qual?"))
        self.label_9.setText(_translate("MainWindow", "Algum periférico foi trocado?"))
        self.txtAttSoftware.setText(_translate("MainWindow", ""))
        self.label_8.setText(_translate("MainWindow", "Há algum periférico faltando?"))
        self.comboBox.setItemText(0, _translate("MainWindow", ""))
        self.comboBox.addItem("Mouse")
        self.comboBox.addItem("MousePad")
        self.comboBox.addItem("Teclado")
        self.comboBox.addItem("WebCam")
        self.comboBox.addItem("HeadFone")
        self.btnEnviar.setText(_translate("MainWindow", "Enviar"))
        self.txtEspDisk.setText(_translate("MainWindow", ""))
        self.label_6.setText(_translate("MainWindow", "Simmmmmm"))
        self.label_15.setText(_translate("MainWindow", "mmmmm"))
        self.radioButton72_2.setText(_translate("MainWindow", "Não"))
        self.radioButton71_2.setText(_translate("MainWindow", "Sim"))
        self.label_3.setText(_translate("MainWindow", "EDV:"))
        self.label_29.setText(_translate("MainWindow", ""))
        self.label_4.setText(_translate("MainWindow", "Usuário:"))
        self.txtEDV.setText(_translate("MainWindow", ""))
        self.txtUser.setText(_translate("MainWindow", ""))
        self.btnOK.setText(_translate("MainWindow", "OK"))

    def nomeHoste(self):
        self.name = socket.gethostname()
        print(self.name)
        self.txtUser.setText(str(self.name))

    def horaSistema(self):
        self.hora = datetime.today().strftime('%H:%M:%S')
        print(type(self.hora))
        self.hora = list(self.hora)
        self.hora = self.hora[:2]
        print(self.hora)
        self.hora = ''.join(self.hora)
        self.hora = int(self.hora)
        if self.hora >=6 and self.hora<=11:
            self.label_29.setText(str("BOM DIA"))
        if self.hora >=12 and self.hora<=17:
            self.label_29.setText("BOA TARDE")
        if self.hora >= 18 and self.hora <= 00:
            self.label_29.setText("BOA NOITE")
        if self.hora >= 00 and self.hora <= 5:
            self.label_29.setText(str("BOA MADRUGADA"))
        print(self.hora)

    def LiberaCB(self, namebutton):
        print(namebutton)
        if namebutton == 'radioButton12':
            self.comboBox.setEnabled(True)
            self.ctrl1 = True

        if namebutton == 'radioButton21':
            self.comboBox_2.setEnabled(True)
            self.ctrl2 = True

        if namebutton == 'radioButton31':
           self.comboBox_3.setEnabled(True)
           self.ctrl3 = True

        if namebutton == 'radioButton41':
            self.comboBox.setEnabled(True)
            self.ctrl4 = True

        if namebutton == 'radioButton51':
            self.txtAttSoftware.setEnabled(True)
            self.ctrl5 = True

        if namebutton == 'radioButton61':
            self.txtAttSoftwareAutorizacao.setEnabled(True)
            self.ctrl6 = True

        if namebutton == 'radioButton71':
            self.ctrl7 = True

        if namebutton == 'radioButton71_2':
            self.txtPastaDel.setEnabled(True)
            self.ctrl8 = True

    def BlockCB(self,namebutton):
        if namebutton == 'radioButton11':
            self.comboBox.setEnabled(False)
            self.comboBox.setCurrentIndex(0)
            self.ctrl1 = False

        if namebutton == 'radioButton22':
            self.comboBox_2.setEnabled(False)
            self.comboBox_2.setCurrentIndex(0)
            self.ctrl2 = False

        if namebutton == 'radioButton32':
           self.comboBox_3.setEnabled(False)
           self.comboBox_3.setCurrentIndex(0)
           self.ctrl3 = False

        if namebutton == 'radioButton42':
            self.comboBox.setEnabled(False)
            self.ctrl4 = False

        if namebutton == 'radioButton52':
            self.txtAttSoftware.setEnabled(False)
            self.ctrl5 = False

        if namebutton == 'radioButton62':
            self.txtAttSoftwareAutorizacao.setEnabled(False)
            self.ctrl6 = False

        if namebutton == 'radioButton72':
            self.ctrl7 = False

        if namebutton == 'radioButton72_2':
            self.txtPastaDel.setEnabled(False)
            self.ctrl8 = False

    def tudoVerificado(self):
        self.ctrlV = 0
        ctrl1B =2
        ctrl2B = 2
        ctrl3B = 2
        ctrl4B = 2
        ctrl5B = 2
        ctrl6B = 2
        ctrl9B = 2
        ctrl8B = 2

        if self.radioButton12.isChecked() or self.radioButton11.isChecked() and self.radioButton21.isChecked() or self.radioButton22.isChecked() and self.radioButton31.isChecked() or self.radioButton32.isChecked() and self.radioButton41.isChecked() or self.radioButton42.isChecked() and self.radioButton51.isChecked() or self.radioButton52.isChecked() and self.radioButton61.isChecked() or self.radioButton62.isChecked() and self.radioButton71.isChecked() or self.radioButton72.isChecked() and self.radioButton71_2.isChecked() or self.radioButton72_2.isChecked():
            self.ctrlV +=1
        print('Valor do ctrl:',self.ctrlV)
        if self.ctrlV == 1:
            print("All RB is checked")
            comboBox1 = self.comboBox.currentText()
            comboBox3 = self.comboBox_3.currentText()
            comboBox2 = self.comboBox_2.currentText()
            txtAttSoftware = self.txtAttSoftware.text()
            obs = self.textEditObs.toPlainText()

            txtPastaDel = self.txtPastaDel.text()
            txtAttSoftwareAutorizacao = self.txtAttSoftwareAutorizacao.text()

            if txtAttSoftwareAutorizacao == '':
                txtAttSoftwareAutorizacao='Null'

            if comboBox1 == '':
                comboBox1='Null'
            if comboBox3 == '':
                comboBox3='Null'

            if comboBox2 == '':
                comboBox2='Null'

            if obs == '':
                obs='Null'

            if txtAttSoftware =='':
                txtAttSoftware ='Null'

            if txtPastaDel =='':
                txtPastaDel ='Null'

            print(comboBox1)
            if self.ctrl1 == True:
                self.ctrl1B = 1

            else:
                self.ctrl1B = 0
            if self.ctrl2 == True:
                self.ctrl2B = 1

            else:
                self.ctrl2B = 0

            if self.ctrl3 == True:
                self.ctrl3B = 1

            else:
                self.ctrl3B = 0
            if self.ctrl4 == True:
                self.ctrl4B = 1

            else:
                self.ctrl4B = 0
            if self.ctrl5 == True:
                self.ctrl5B = 1

            else:
                self.ctrl5B = 0
            if self.ctrl6 == True:
                self.ctrl6B = 1

            else:
                self.ctrl6B = 0
            if self.ctrl7 == True:
                self.ctrl7B = 1

            else:
                self.ctrl7B = 0
            if self.ctrl8 == True:
                self.ctrl8B = 1

            else:
                self.ctrl8B = 0

            print('PerFaltando:',self.ctrl1B)
            print('qualPerfFaltando:',comboBox1)
            print('perfTrocado:',self.ctrl2B)
            print('qualPerfTrocado:',comboBox2)
            print('perfProblema:',self.ctrl3B)
            print('qualperfProblema:',comboBox3)
            print('desktopLimpo:',self.ctrl4B)
            print('attSoftware:',self.ctrl5B)
            print('qualattSoftware:',txtAttSoftware)
            print('pastaMovida:',self.ctrl6B)
            print('qualpastaMovida:',txtPastaDel)
            print('autorizacaoSoftware:',self.ctrl7B)
            print('qualautorizacaoSoftware:',txtAttSoftwareAutorizacao)
            print('espDisco:',self.ctrl8B)
            print('obs:',obs)
            print('edvFK:',self.edvInt)

            self.cursor.execute("UPDATE `verifica"
                                "cao` SET `perfFaltando`={},`qualPerfFaltando`='{}',`perfTrocado`={}, `qualPerfTrocado`='{}', `perfProblema`={},`qualperfProblema`='{}',`desktopLimpo`={},`attSoftware`={},`qualattSoftware`='{}',`pastaMovida`={},`qualpastaMovida`='{}',`autorizacaoSoftware`={},`qualautorizacaoSoftware`='{}',`espDisco`={},`obs`='{}' WHERE verificacao.edvFK = {}".format(self.ctrl1B,comboBox1,self.ctrl2B,comboBox2,self.ctrl3B,comboBox3,self.ctrl4B,self.ctrl5B,txtAttSoftware,self.ctrl6B,txtPastaDel,self.ctrl7B,txtAttSoftwareAutorizacao,self.ctrl8B,obs,self.edvInt))

            self.con.commit()
            print(self.cursor.rowcount, "record inserted.")

            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("CheckList Realizado!\n Até Amanhã :)")
            msg.exec()
            self.txtEDV.setText('')

        else:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("Preencha todos os campos!!" )
            msg.exec()
            self.txtEDV.setText('')

    def conxaoDB(self):
        if self.con.is_connected():
            db_info = self.con.get_server_info()
            print("Conectado ao servidor MySQL versão:  ", db_info)

    def verificaEDV(self):
        self.horaBD = datetime.today().strftime('%Y-%m-%d %H:%M:%S')

        self.edv = self.txtEDV.text()

        self.edvInt = int(self.edv)
        print(self.edvInt)
        self.cursor.execute("SELECT edv FROM colaborador edv={}".format(edv))
        myresult = self.cursor.fetchall()
        if myresult != '':
            print("dados nao encontrados!")

        myresult = str(myresult)
        print(myresult)
        print('hora: ',self.horaBD)
        if myresult != '[]':
            nomePC=str(self.txtUser.text())

            self.cursor.execute("SELECT codPC FROM desktop where nomePC='{}'".format(nomePC))
            myresult2 = self.cursor.fetchone()
            myresult2 = int(myresult2[0])
            print(myresult2)

            self.widget.setEnabled(True)
            self.txtEDV.setEnabled(True)
            self.btnOK.setEnabled(False)
            self.hora = str(self.hora)

            self.cursor.execute("INSERT INTO verificacao VALUES ({},{},'2','','2','','2','','2','2','','2','','2','','2','','{}')".format(self.edvInt,myresult2,self.horaBD))

            self.con.commit()
            print(self.cursor.rowcount, "record inserted.")

        else:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("EDV não encontrado!")
            msg.exec()
            self.txtEDV.setText('')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

